// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mcchain/edgeai/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the edgeai module (B3).
type Params struct {
	// dispute_period_blocks 争议期（区块数），结果提交后此期限内可被挑战。
	DisputePeriodBlocks int64 `protobuf:"varint,1,opt,name=dispute_period_blocks,json=disputePeriodBlocks,proto3" json:"dispute_period_blocks,omitempty"`
	// anti_cheat_threshold_bps 反作弊阈值（基点），超过处罚门槛。
	AntiCheatThresholdBps uint32 `protobuf:"varint,2,opt,name=anti_cheat_threshold_bps,json=antiCheatThresholdBps,proto3" json:"anti_cheat_threshold_bps,omitempty"`
	// max_task_reward 单任务最大奖励（umc 字符串，防溢出）。
	MaxTaskReward string `protobuf:"bytes,3,opt,name=max_task_reward,json=maxTaskReward,proto3" json:"max_task_reward,omitempty"`
	// arbitrator B3.1 争议仲裁者地址（部署时设为团队多签地址）。
	// 为空表示尚未配置，ResolveDispute 将被拒绝。
	Arbitrator string `protobuf:"bytes,4,opt,name=arbitrator,proto3" json:"arbitrator,omitempty"`
	// verifier_count 多验证者投票评分系统中每轮抽检的验证者数量（默认 3）。
	// TODO: 待 protoc 重新生成后生效，当前以模块常量 DefaultVerifierCount 兜底。
	VerifierCount uint32 `protobuf:"varint,5,opt,name=verifier_count,json=verifierCount,proto3" json:"verifier_count,omitempty"`
	// threshold_score 验证评分阈值（0-100），中位数低于此值则拒绝并进入争议（默认 30）。
	// TODO: 待 protoc 重新生成后生效，当前以模块常量 DefaultThresholdScore 兜底。
	ThresholdScore uint32 `protobuf:"varint,6,opt,name=threshold_score,json=thresholdScore,proto3" json:"threshold_score,omitempty"`
	// default_script_timeout 验证脚本默认超时时间（秒，默认 30）。
	// TODO: 待 protoc 重新生成后生效，当前以模块常量 DefaultScriptTimeout 兜底。
	DefaultScriptTimeout uint32 `protobuf:"varint,7,opt,name=default_script_timeout,json=defaultScriptTimeout,proto3" json:"default_script_timeout,omitempty"`
	// script_network_allowed 验证脚本是否默认允许网络访问（默认 false）。
	// TODO: 待 protoc 重新生成后生效，当前以模块常量 DefaultScriptNetworkAllowed 兜底。
	ScriptNetworkAllowed bool `protobuf:"varint,8,opt,name=script_network_allowed,json=scriptNetworkAllowed,proto3" json:"script_network_allowed,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d338cd330eb85d0, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDisputePeriodBlocks() int64 {
	if m != nil {
		return m.DisputePeriodBlocks
	}
	return 0
}

func (m *Params) GetAntiCheatThresholdBps() uint32 {
	if m != nil {
		return m.AntiCheatThresholdBps
	}
	return 0
}

func (m *Params) GetMaxTaskReward() string {
	if m != nil {
		return m.MaxTaskReward
	}
	return ""
}

func (m *Params) GetArbitrator() string {
	if m != nil {
		return m.Arbitrator
	}
	return ""
}

func (m *Params) GetVerifierCount() uint32 {
	if m != nil {
		return m.VerifierCount
	}
	return 0
}

func (m *Params) GetThresholdScore() uint32 {
	if m != nil {
		return m.ThresholdScore
	}
	return 0
}

func (m *Params) GetDefaultScriptTimeout() uint32 {
	if m != nil {
		return m.DefaultScriptTimeout
	}
	return 0
}

func (m *Params) GetScriptNetworkAllowed() bool {
	if m != nil {
		return m.ScriptNetworkAllowed
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "mcchain.edgeai.Params")
}

func init() { proto.RegisterFile("mcchain/edgeai/params.proto", fileDescriptor_8d338cd330eb85d0) }

var fileDescriptor_8d338cd330eb85d0 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd1, 0x3d, 0x8b, 0xdb, 0x30,
	0x1c, 0x06, 0x70, 0x2b, 0x49, 0xd3, 0x54, 0x90, 0x04, 0xd4, 0x24, 0x88, 0x16, 0x5c, 0x53, 0x68,
	0xeb, 0x29, 0x29, 0x6d, 0xa1, 0xd0, 0xad, 0xc9, 0x5e, 0x82, 0x93, 0xa9, 0x8b, 0x90, 0x6d, 0x25,
	0x16, 0x7e, 0x91, 0x90, 0xe4, 0x26, 0xfd, 0x16, 0x37, 0xde, 0x78, 0x1f, 0xe7, 0xc6, 0x8c, 0x37,
	0x1e, 0xc9, 0x07, 0xb9, 0xc3, 0xb2, 0x7d, 0x77, 0x9b, 0x79, 0x7e, 0xcf, 0x1f, 0x0b, 0x1e, 0xf8,
	0x3e, 0x8f, 0xa2, 0x84, 0xf2, 0x62, 0xc1, 0xe2, 0x3d, 0xa3, 0x7c, 0x21, 0xa9, 0xa2, 0xb9, 0x9e,
	0x4b, 0x25, 0x8c, 0x40, 0xa3, 0x06, 0xe7, 0x35, 0xbe, 0x9b, 0xec, 0xc5, 0x5e, 0x58, 0x5a, 0x54,
	0x5f, 0x75, 0xeb, 0xe3, 0x43, 0x07, 0xf6, 0xd7, 0xf6, 0x0c, 0x7d, 0x83, 0xd3, 0x98, 0x6b, 0x59,
	0x1a, 0x46, 0x24, 0x53, 0x5c, 0xc4, 0x24, 0xcc, 0x44, 0x94, 0x6a, 0x0c, 0x3c, 0xe0, 0x77, 0x83,
	0xb7, 0x0d, 0xae, 0xad, 0x2d, 0x2d, 0xa1, 0x9f, 0x10, 0xd3, 0xc2, 0x70, 0x12, 0x25, 0x8c, 0x1a,
	0x62, 0x12, 0xc5, 0x74, 0x22, 0xb2, 0x98, 0x84, 0x52, 0xe3, 0x8e, 0x07, 0xfc, 0x61, 0x30, 0xad,
	0x7c, 0x55, 0xf1, 0xb6, 0xd5, 0xa5, 0xd4, 0xe8, 0x33, 0x1c, 0xe7, 0xf4, 0x48, 0x0c, 0xd5, 0x29,
	0x51, 0xec, 0x40, 0x55, 0x8c, 0xbb, 0x1e, 0xf0, 0xdf, 0x04, 0xc3, 0x9c, 0x1e, 0xb7, 0x54, 0xa7,
	0x81, 0x0d, 0x91, 0x0b, 0x21, 0x55, 0x21, 0x37, 0x8a, 0x1a, 0xa1, 0x70, 0xcf, 0x56, 0x5e, 0x24,
	0xe8, 0x13, 0x1c, 0xfd, 0x63, 0x8a, 0xef, 0x38, 0x53, 0x24, 0x12, 0x65, 0x61, 0xf0, 0x2b, 0xfb,
	0xdb, 0x61, 0x9b, 0xae, 0xaa, 0x10, 0x7d, 0x81, 0xe3, 0xe7, 0xc7, 0xe9, 0x48, 0x28, 0x86, 0xfb,
	0xb6, 0x37, 0x7a, 0x8a, 0x37, 0x55, 0x8a, 0x7e, 0xc0, 0x59, 0xcc, 0x76, 0xb4, 0xcc, 0x0c, 0xd1,
	0x91, 0xe2, 0xd2, 0x10, 0xc3, 0x73, 0x26, 0x4a, 0x83, 0x5f, 0xdb, 0xfe, 0xa4, 0xd1, 0x8d, 0xc5,
	0x6d, 0x6d, 0xd5, 0x55, 0xd3, 0x2e, 0x98, 0x39, 0x08, 0x95, 0x12, 0x9a, 0x65, 0xe2, 0xc0, 0x62,
	0x3c, 0xf0, 0x80, 0x3f, 0x08, 0x26, 0xb5, 0xfe, 0xa9, 0xf1, 0x77, 0x6d, 0xbf, 0x7a, 0xd7, 0x37,
	0x1f, 0x9c, 0xe5, 0xd7, 0xdb, 0xb3, 0x0b, 0x4e, 0x67, 0x17, 0xdc, 0x9f, 0x5d, 0x70, 0x75, 0x71,
	0x9d, 0xd3, 0xc5, 0x75, 0xee, 0x2e, 0xae, 0xf3, 0x77, 0xd6, 0xce, 0x7b, 0x6c, 0x07, 0x36, 0xff,
	0x25, 0xd3, 0x61, 0xdf, 0x4e, 0xf7, 0xfd, 0x31, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x9f, 0xb1, 0x2d,
	0xff, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ScriptNetworkAllowed {
		i--
		if m.ScriptNetworkAllowed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.DefaultScriptTimeout != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DefaultScriptTimeout))
		i--
		dAtA[i] = 0x38
	}
	if m.ThresholdScore != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ThresholdScore))
		i--
		dAtA[i] = 0x30
	}
	if m.VerifierCount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.VerifierCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Arbitrator) > 0 {
		i -= len(m.Arbitrator)
		copy(dAtA[i:], m.Arbitrator)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Arbitrator)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MaxTaskReward) > 0 {
		i -= len(m.MaxTaskReward)
		copy(dAtA[i:], m.MaxTaskReward)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MaxTaskReward)))
		i--
		dAtA[i] = 0x1a
	}
	if m.AntiCheatThresholdBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AntiCheatThresholdBps))
		i--
		dAtA[i] = 0x10
	}
	if m.DisputePeriodBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DisputePeriodBlocks))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DisputePeriodBlocks != 0 {
		n += 1 + sovParams(uint64(m.DisputePeriodBlocks))
	}
	if m.AntiCheatThresholdBps != 0 {
		n += 1 + sovParams(uint64(m.AntiCheatThresholdBps))
	}
	l = len(m.MaxTaskReward)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.Arbitrator)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.VerifierCount != 0 {
		n += 1 + sovParams(uint64(m.VerifierCount))
	}
	if m.ThresholdScore != 0 {
		n += 1 + sovParams(uint64(m.ThresholdScore))
	}
	if m.DefaultScriptTimeout != 0 {
		n += 1 + sovParams(uint64(m.DefaultScriptTimeout))
	}
	if m.ScriptNetworkAllowed {
		n += 2
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputePeriodBlocks", wireType)
			}
			m.DisputePeriodBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DisputePeriodBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AntiCheatThresholdBps", wireType)
			}
			m.AntiCheatThresholdBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AntiCheatThresholdBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTaskReward", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxTaskReward = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Arbitrator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Arbitrator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierCount", wireType)
			}
			m.VerifierCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifierCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ThresholdScore", wireType)
			}
			m.ThresholdScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ThresholdScore |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultScriptTimeout", wireType)
			}
			m.DefaultScriptTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultScriptTimeout |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScriptNetworkAllowed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ScriptNetworkAllowed = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
