// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mcchain/referral/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the referral module.
type Params struct {
	Level1RewardRateBps uint32 `protobuf:"varint,1,opt,name=level1_reward_rate_bps,json=level1RewardRateBps,proto3" json:"level1_reward_rate_bps,omitempty"`
	Level2RewardRateBps uint32 `protobuf:"varint,2,opt,name=level2_reward_rate_bps,json=level2RewardRateBps,proto3" json:"level2_reward_rate_bps,omitempty"`
	Level3RewardRateBps uint32 `protobuf:"varint,3,opt,name=level3_reward_rate_bps,json=level3RewardRateBps,proto3" json:"level3_reward_rate_bps,omitempty"`
	MinPayout           string `protobuf:"bytes,4,opt,name=min_payout,json=minPayout,proto3" json:"min_payout,omitempty"`
	MaxReferralsPerUser uint64 `protobuf:"varint,5,opt,name=max_referrals_per_user,json=maxReferralsPerUser,proto3" json:"max_referrals_per_user,omitempty"`
	CooldownBlocks      uint64 `protobuf:"varint,6,opt,name=cooldown_blocks,json=cooldownBlocks,proto3" json:"cooldown_blocks,omitempty"`
	DailyPerUserCap     uint64 `protobuf:"varint,7,opt,name=daily_per_user_cap,json=dailyPerUserCap,proto3" json:"daily_per_user_cap,omitempty"`
	DailyNetworkCap     uint64 `protobuf:"varint,8,opt,name=daily_network_cap,json=dailyNetworkCap,proto3" json:"daily_network_cap,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_d07f13c1e96ff7a6, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetLevel1RewardRateBps() uint32 {
	if m != nil {
		return m.Level1RewardRateBps
	}
	return 0
}

func (m *Params) GetLevel2RewardRateBps() uint32 {
	if m != nil {
		return m.Level2RewardRateBps
	}
	return 0
}

func (m *Params) GetLevel3RewardRateBps() uint32 {
	if m != nil {
		return m.Level3RewardRateBps
	}
	return 0
}

func (m *Params) GetMinPayout() string {
	if m != nil {
		return m.MinPayout
	}
	return ""
}

func (m *Params) GetMaxReferralsPerUser() uint64 {
	if m != nil {
		return m.MaxReferralsPerUser
	}
	return 0
}

func (m *Params) GetCooldownBlocks() uint64 {
	if m != nil {
		return m.CooldownBlocks
	}
	return 0
}

func (m *Params) GetDailyPerUserCap() uint64 {
	if m != nil {
		return m.DailyPerUserCap
	}
	return 0
}

func (m *Params) GetDailyNetworkCap() uint64 {
	if m != nil {
		return m.DailyNetworkCap
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "mcchain.referral.Params")
}

func init() { proto.RegisterFile("mcchain/referral/params.proto", fileDescriptor_d07f13c1e96ff7a6) }

var fileDescriptor_d07f13c1e96ff7a6 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0x3a, 0x41,
	0x18, 0xc6, 0x1d, 0xff, 0xfe, 0x2d, 0x07, 0xca, 0x5a, 0x23, 0x96, 0xc0, 0x45, 0xba, 0x24, 0x05,
	0x4a, 0xee, 0x37, 0xd0, 0x7b, 0xc8, 0x42, 0x97, 0x2e, 0xc3, 0xeb, 0xfa, 0x66, 0x8b, 0xbb, 0x3b,
	0xc3, 0x3b, 0x63, 0xea, 0xb7, 0xe8, 0x63, 0x75, 0xf4, 0xd8, 0x31, 0xf4, 0x73, 0x04, 0xe1, 0xac,
	0x9b, 0x1b, 0x76, 0x1b, 0x9e, 0xdf, 0xf3, 0x7b, 0x61, 0x78, 0x78, 0x33, 0x09, 0xc3, 0x17, 0x88,
	0xd2, 0x2e, 0xe1, 0x33, 0x12, 0x41, 0xdc, 0x55, 0x40, 0x90, 0xe8, 0x8e, 0x22, 0x69, 0xa4, 0x73,
	0xb6, 0xc3, 0x9d, 0x1c, 0x5f, 0x5d, 0x4c, 0xe4, 0x44, 0x5a, 0xd8, 0xdd, 0xbe, 0xb2, 0xde, 0xf5,
	0x57, 0x99, 0x57, 0x87, 0x56, 0x74, 0x7c, 0x7e, 0x19, 0xe3, 0x2b, 0xc6, 0xf7, 0x82, 0x70, 0x0e,
	0x34, 0x16, 0x04, 0x06, 0xc5, 0x48, 0x69, 0x97, 0xb5, 0x58, 0xfb, 0x24, 0x68, 0x64, 0x34, 0xb0,
	0x30, 0x00, 0x83, 0x7d, 0xb5, 0x97, 0x7a, 0x07, 0x52, 0xb9, 0x20, 0xf5, 0xfe, 0x96, 0xfc, 0x03,
	0xe9, 0x5f, 0x41, 0xf2, 0x7f, 0x4b, 0x4d, 0xce, 0x93, 0x28, 0x15, 0x0a, 0x96, 0x72, 0x66, 0xdc,
	0x4a, 0x8b, 0xb5, 0x6b, 0x41, 0x2d, 0x89, 0xd2, 0xa1, 0x0d, 0xb6, 0x37, 0x13, 0x58, 0x88, 0xfc,
	0xbb, 0x5a, 0x28, 0x24, 0x31, 0xd3, 0x48, 0xee, 0xff, 0x16, 0x6b, 0x57, 0x82, 0x46, 0x02, 0x8b,
	0x20, 0x87, 0x43, 0xa4, 0x47, 0x8d, 0xe4, 0xdc, 0xf0, 0x7a, 0x28, 0x65, 0x3c, 0x96, 0xf3, 0x54,
	0x8c, 0x62, 0x19, 0x4e, 0xb5, 0x5b, 0xb5, 0xed, 0xd3, 0x3c, 0xee, 0xdb, 0xd4, 0xb9, 0xe3, 0xce,
	0x18, 0xa2, 0x78, 0xf9, 0x73, 0x55, 0x84, 0xa0, 0xdc, 0x23, 0xdb, 0xad, 0x5b, 0xb2, 0x3b, 0x39,
	0x00, 0xe5, 0xdc, 0xf2, 0xf3, 0xac, 0x9c, 0xa2, 0x99, 0x4b, 0x9a, 0xda, 0xee, 0x71, 0xa1, 0xfb,
	0x90, 0xe5, 0x03, 0x50, 0xfd, 0xde, 0xfb, 0xda, 0x63, 0xab, 0xb5, 0xc7, 0x3e, 0xd7, 0x1e, 0x7b,
	0xdb, 0x78, 0xa5, 0xd5, 0xc6, 0x2b, 0x7d, 0x6c, 0xbc, 0xd2, 0x93, 0x9b, 0x0f, 0xbc, 0xd8, 0x4f,
	0x6c, 0x96, 0x0a, 0xf5, 0xa8, 0x6a, 0xa7, 0xf3, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x42,
	0x0a, 0x26, 0x03, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DailyNetworkCap != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DailyNetworkCap))
		i--
		dAtA[i] = 0x40
	}
	if m.DailyPerUserCap != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DailyPerUserCap))
		i--
		dAtA[i] = 0x38
	}
	if m.CooldownBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CooldownBlocks))
		i--
		dAtA[i] = 0x30
	}
	if m.MaxReferralsPerUser != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxReferralsPerUser))
		i--
		dAtA[i] = 0x28
	}
	if len(m.MinPayout) > 0 {
		i -= len(m.MinPayout)
		copy(dAtA[i:], m.MinPayout)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MinPayout)))
		i--
		dAtA[i] = 0x22
	}
	if m.Level3RewardRateBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.Level3RewardRateBps))
		i--
		dAtA[i] = 0x18
	}
	if m.Level2RewardRateBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.Level2RewardRateBps))
		i--
		dAtA[i] = 0x10
	}
	if m.Level1RewardRateBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.Level1RewardRateBps))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Level1RewardRateBps != 0 {
		n += 1 + sovParams(uint64(m.Level1RewardRateBps))
	}
	if m.Level2RewardRateBps != 0 {
		n += 1 + sovParams(uint64(m.Level2RewardRateBps))
	}
	if m.Level3RewardRateBps != 0 {
		n += 1 + sovParams(uint64(m.Level3RewardRateBps))
	}
	l = len(m.MinPayout)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.MaxReferralsPerUser != 0 {
		n += 1 + sovParams(uint64(m.MaxReferralsPerUser))
	}
	if m.CooldownBlocks != 0 {
		n += 1 + sovParams(uint64(m.CooldownBlocks))
	}
	if m.DailyPerUserCap != 0 {
		n += 1 + sovParams(uint64(m.DailyPerUserCap))
	}
	if m.DailyNetworkCap != 0 {
		n += 1 + sovParams(uint64(m.DailyNetworkCap))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Level1RewardRateBps", wireType)
			}
			m.Level1RewardRateBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Level1RewardRateBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Level2RewardRateBps", wireType)
			}
			m.Level2RewardRateBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Level2RewardRateBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Level3RewardRateBps", wireType)
			}
			m.Level3RewardRateBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Level3RewardRateBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinPayout", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinPayout = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxReferralsPerUser", wireType)
			}
			m.MaxReferralsPerUser = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxReferralsPerUser |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CooldownBlocks", wireType)
			}
			m.CooldownBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CooldownBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DailyPerUserCap", wireType)
			}
			m.DailyPerUserCap = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DailyPerUserCap |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DailyNetworkCap", wireType)
			}
			m.DailyNetworkCap = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DailyNetworkCap |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
