// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mcchain/referral/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryReferralRequest struct {
	ReferralId uint64 `protobuf:"varint,1,opt,name=referral_id,json=referralId,proto3" json:"referral_id,omitempty"`
}

func (m *QueryReferralRequest) Reset()         { *m = QueryReferralRequest{} }
func (m *QueryReferralRequest) String() string { return proto.CompactTextString(m) }
func (*QueryReferralRequest) ProtoMessage()    {}
func (*QueryReferralRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd123dd1415758b, []int{0}
}
func (m *QueryReferralRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReferralRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReferralRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReferralRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReferralRequest.Merge(m, src)
}
func (m *QueryReferralRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryReferralRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReferralRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReferralRequest proto.InternalMessageInfo

func (m *QueryReferralRequest) GetReferralId() uint64 {
	if m != nil {
		return m.ReferralId
	}
	return 0
}

type QueryReferralResponse struct {
	Referral Referral `protobuf:"bytes,1,opt,name=referral,proto3" json:"referral"`
}

func (m *QueryReferralResponse) Reset()         { *m = QueryReferralResponse{} }
func (m *QueryReferralResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReferralResponse) ProtoMessage()    {}
func (*QueryReferralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd123dd1415758b, []int{1}
}
func (m *QueryReferralResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReferralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReferralResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReferralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReferralResponse.Merge(m, src)
}
func (m *QueryReferralResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryReferralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReferralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReferralResponse proto.InternalMessageInfo

func (m *QueryReferralResponse) GetReferral() Referral {
	if m != nil {
		return m.Referral
	}
	return Referral{}
}

type QueryReferralsByInviterRequest struct {
	Inviter string `protobuf:"bytes,1,opt,name=inviter,proto3" json:"inviter,omitempty"`
}

func (m *QueryReferralsByInviterRequest) Reset()         { *m = QueryReferralsByInviterRequest{} }
func (m *QueryReferralsByInviterRequest) String() string { return proto.CompactTextString(m) }
func (*QueryReferralsByInviterRequest) ProtoMessage()    {}
func (*QueryReferralsByInviterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd123dd1415758b, []int{2}
}
func (m *QueryReferralsByInviterRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReferralsByInviterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReferralsByInviterRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReferralsByInviterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReferralsByInviterRequest.Merge(m, src)
}
func (m *QueryReferralsByInviterRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryReferralsByInviterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReferralsByInviterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReferralsByInviterRequest proto.InternalMessageInfo

func (m *QueryReferralsByInviterRequest) GetInviter() string {
	if m != nil {
		return m.Inviter
	}
	return ""
}

type QueryReferralsByInviterResponse struct {
	Referrals []Referral `protobuf:"bytes,1,rep,name=referrals,proto3" json:"referrals"`
}

func (m *QueryReferralsByInviterResponse) Reset()         { *m = QueryReferralsByInviterResponse{} }
func (m *QueryReferralsByInviterResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReferralsByInviterResponse) ProtoMessage()    {}
func (*QueryReferralsByInviterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd123dd1415758b, []int{3}
}
func (m *QueryReferralsByInviterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReferralsByInviterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReferralsByInviterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReferralsByInviterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReferralsByInviterResponse.Merge(m, src)
}
func (m *QueryReferralsByInviterResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryReferralsByInviterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReferralsByInviterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReferralsByInviterResponse proto.InternalMessageInfo

func (m *QueryReferralsByInviterResponse) GetReferrals() []Referral {
	if m != nil {
		return m.Referrals
	}
	return nil
}

type QueryPendingRewardsRequest struct {
	Claimer string `protobuf:"bytes,1,opt,name=claimer,proto3" json:"claimer,omitempty"`
}

func (m *QueryPendingRewardsRequest) Reset()         { *m = QueryPendingRewardsRequest{} }
func (m *QueryPendingRewardsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPendingRewardsRequest) ProtoMessage()    {}
func (*QueryPendingRewardsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd123dd1415758b, []int{4}
}
func (m *QueryPendingRewardsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingRewardsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingRewardsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingRewardsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingRewardsRequest.Merge(m, src)
}
func (m *QueryPendingRewardsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingRewardsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingRewardsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingRewardsRequest proto.InternalMessageInfo

func (m *QueryPendingRewardsRequest) GetClaimer() string {
	if m != nil {
		return m.Claimer
	}
	return ""
}

type QueryPendingRewardsResponse struct {
	Amount string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *QueryPendingRewardsResponse) Reset()         { *m = QueryPendingRewardsResponse{} }
func (m *QueryPendingRewardsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPendingRewardsResponse) ProtoMessage()    {}
func (*QueryPendingRewardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd123dd1415758b, []int{5}
}
func (m *QueryPendingRewardsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingRewardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingRewardsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingRewardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingRewardsResponse.Merge(m, src)
}
func (m *QueryPendingRewardsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingRewardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingRewardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingRewardsResponse proto.InternalMessageInfo

func (m *QueryPendingRewardsResponse) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// Referral represents a single referral record stored on-chain.
type Referral struct {
	ReferralId uint64 `protobuf:"varint,1,opt,name=referral_id,json=referralId,proto3" json:"referral_id,omitempty"`
	Inviter    string `protobuf:"bytes,2,opt,name=inviter,proto3" json:"inviter,omitempty"`
	Invitee    string `protobuf:"bytes,3,opt,name=invitee,proto3" json:"invitee,omitempty"`
	InviteCode string `protobuf:"bytes,4,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	CreatedAt  int64  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status     string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *Referral) Reset()         { *m = Referral{} }
func (m *Referral) String() string { return proto.CompactTextString(m) }
func (*Referral) ProtoMessage()    {}
func (*Referral) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd123dd1415758b, []int{6}
}
func (m *Referral) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Referral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Referral.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Referral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Referral.Merge(m, src)
}
func (m *Referral) XXX_Size() int {
	return m.Size()
}
func (m *Referral) XXX_DiscardUnknown() {
	xxx_messageInfo_Referral.DiscardUnknown(m)
}

var xxx_messageInfo_Referral proto.InternalMessageInfo

func (m *Referral) GetReferralId() uint64 {
	if m != nil {
		return m.ReferralId
	}
	return 0
}

func (m *Referral) GetInviter() string {
	if m != nil {
		return m.Inviter
	}
	return ""
}

func (m *Referral) GetInvitee() string {
	if m != nil {
		return m.Invitee
	}
	return ""
}

func (m *Referral) GetInviteCode() string {
	if m != nil {
		return m.InviteCode
	}
	return ""
}

func (m *Referral) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Referral) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryReferralRequest)(nil), "mcchain.referral.QueryReferralRequest")
	proto.RegisterType((*QueryReferralResponse)(nil), "mcchain.referral.QueryReferralResponse")
	proto.RegisterType((*QueryReferralsByInviterRequest)(nil), "mcchain.referral.QueryReferralsByInviterRequest")
	proto.RegisterType((*QueryReferralsByInviterResponse)(nil), "mcchain.referral.QueryReferralsByInviterResponse")
	proto.RegisterType((*QueryPendingRewardsRequest)(nil), "mcchain.referral.QueryPendingRewardsRequest")
	proto.RegisterType((*QueryPendingRewardsResponse)(nil), "mcchain.referral.QueryPendingRewardsResponse")
	proto.RegisterType((*Referral)(nil), "mcchain.referral.Referral")
}

func init() { proto.RegisterFile("mcchain/referral/query.proto", fileDescriptor_1fd123dd1415758b) }

var fileDescriptor_1fd123dd1415758b = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0x5d, 0x37, 0x69, 0x68, 0xa6, 0x12, 0x42, 0x56, 0x41, 0xd6, 0x02, 0x9b, 0xc8, 0x07, 0xe8,
	0x01, 0x12, 0x08, 0x02, 0x24, 0x84, 0x90, 0x08, 0xa7, 0xde, 0x60, 0x25, 0x2e, 0x48, 0x28, 0x32,
	0xbb, 0x43, 0x58, 0xa9, 0x59, 0xa7, 0xb6, 0x17, 0x88, 0xf8, 0x09, 0xfe, 0x86, 0x5f, 0xe8, 0xb1,
	0x07, 0x0e, 0x9c, 0x10, 0x4a, 0x7e, 0x04, 0xed, 0xae, 0xdd, 0xdd, 0x34, 0xa9, 0x92, 0xde, 0x3c,
	0xf3, 0xe6, 0xcd, 0x3c, 0xcf, 0x8c, 0x0d, 0x77, 0x26, 0x51, 0xf4, 0x45, 0x24, 0x69, 0x5f, 0xe1,
	0x67, 0x54, 0x4a, 0x1c, 0xf7, 0x4f, 0x32, 0x54, 0xb3, 0xde, 0x54, 0x49, 0x23, 0xe9, 0x0d, 0x8b,
	0xf6, 0x1c, 0xea, 0x1f, 0x8c, 0xe5, 0x58, 0x16, 0x60, 0x3f, 0x3f, 0x95, 0x71, 0xfc, 0x39, 0x1c,
	0xbc, 0xcb, 0x69, 0xa1, 0x0d, 0x0b, 0xf1, 0x24, 0x43, 0x6d, 0x68, 0x07, 0xf6, 0x1d, 0x73, 0x94,
	0xc4, 0x8c, 0x74, 0xc9, 0x61, 0x33, 0x04, 0xe7, 0x3a, 0x8a, 0xf9, 0x7b, 0xb8, 0x79, 0x81, 0xa8,
	0xa7, 0x32, 0xd5, 0x48, 0x5f, 0xc2, 0x9e, 0x0b, 0x2b, 0x68, 0xfb, 0x03, 0xbf, 0x77, 0x51, 0x4c,
	0xcf, 0xb1, 0x86, 0xcd, 0xd3, 0xbf, 0x1d, 0x2f, 0x3c, 0x67, 0xf0, 0x17, 0x10, 0x2c, 0xa5, 0xd5,
	0xc3, 0xd9, 0x51, 0xfa, 0x35, 0x31, 0xa8, 0x9c, 0x32, 0x06, 0xd7, 0x92, 0xd2, 0x53, 0xa4, 0x6f,
	0x87, 0xce, 0xe4, 0x02, 0x3a, 0x97, 0x72, 0xad, 0xb8, 0x57, 0xd0, 0x76, 0xa5, 0x34, 0x23, 0xdd,
	0xc6, 0x56, 0xea, 0x2a, 0x0a, 0x7f, 0x06, 0x7e, 0x51, 0xe2, 0x2d, 0xa6, 0x71, 0x92, 0x8e, 0x43,
	0xfc, 0x26, 0x54, 0xac, 0x6b, 0xd2, 0xa2, 0x63, 0x91, 0x4c, 0x2a, 0x69, 0xd6, 0xe4, 0x4f, 0xe1,
	0xf6, 0x5a, 0x9e, 0x95, 0x75, 0x0b, 0x5a, 0x62, 0x22, 0xb3, 0xd4, 0x58, 0x9e, 0xb5, 0xf8, 0x2f,
	0x02, 0x7b, 0x4e, 0xcc, 0xc6, 0x91, 0xd4, 0x3b, 0xb3, 0xb3, 0xd4, 0x99, 0x0a, 0x41, 0xd6, 0xa8,
	0x23, 0x98, 0x27, 0x2d, 0x8f, 0xa3, 0x48, 0xc6, 0xc8, 0x9a, 0x05, 0x0a, 0xa5, 0xeb, 0x8d, 0x8c,
	0x91, 0xde, 0x05, 0x88, 0x14, 0x0a, 0x83, 0xf1, 0x48, 0x18, 0xb6, 0xdb, 0x25, 0x87, 0x8d, 0xb0,
	0x6d, 0x3d, 0xaf, 0x4d, 0xae, 0x5c, 0x1b, 0x61, 0x32, 0xcd, 0x5a, 0xa5, 0xf2, 0xd2, 0x1a, 0xfc,
	0xde, 0x81, 0xdd, 0xe2, 0xc6, 0xf4, 0x63, 0xed, 0x0a, 0xf7, 0x56, 0x7b, 0xbd, 0x6e, 0xfb, 0xfc,
	0xfb, 0x1b, 0xe3, 0xca, 0xc6, 0x71, 0x8f, 0xfe, 0x00, 0xba, 0x3a, 0x6f, 0xfa, 0x68, 0x43, 0x82,
	0x95, 0xb5, 0xf2, 0x1f, 0x5f, 0x81, 0x71, 0x5e, 0x5c, 0xc2, 0xf5, 0xe5, 0x89, 0xd2, 0x07, 0x97,
	0xa4, 0x59, 0xbb, 0x30, 0xfe, 0xc3, 0x2d, 0xa3, 0x5d, 0xc1, 0xe1, 0xe0, 0x74, 0x1e, 0x90, 0xb3,
	0x79, 0x40, 0xfe, 0xcd, 0x03, 0xf2, 0x73, 0x11, 0x78, 0x67, 0x8b, 0xc0, 0xfb, 0xb3, 0x08, 0xbc,
	0x0f, 0xcc, 0x7d, 0x07, 0xdf, 0xab, 0x0f, 0xc1, 0xcc, 0xa6, 0xa8, 0x3f, 0xb5, 0x8a, 0x97, 0xfe,
	0xe4, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xd8, 0x6b, 0x64, 0x31, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Referral(ctx context.Context, in *QueryReferralRequest, opts ...grpc.CallOption) (*QueryReferralResponse, error)
	ReferralsByInviter(ctx context.Context, in *QueryReferralsByInviterRequest, opts ...grpc.CallOption) (*QueryReferralsByInviterResponse, error)
	PendingRewards(ctx context.Context, in *QueryPendingRewardsRequest, opts ...grpc.CallOption) (*QueryPendingRewardsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Referral(ctx context.Context, in *QueryReferralRequest, opts ...grpc.CallOption) (*QueryReferralResponse, error) {
	out := new(QueryReferralResponse)
	err := c.cc.Invoke(ctx, "/mcchain.referral.Query/Referral", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ReferralsByInviter(ctx context.Context, in *QueryReferralsByInviterRequest, opts ...grpc.CallOption) (*QueryReferralsByInviterResponse, error) {
	out := new(QueryReferralsByInviterResponse)
	err := c.cc.Invoke(ctx, "/mcchain.referral.Query/ReferralsByInviter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingRewards(ctx context.Context, in *QueryPendingRewardsRequest, opts ...grpc.CallOption) (*QueryPendingRewardsResponse, error) {
	out := new(QueryPendingRewardsResponse)
	err := c.cc.Invoke(ctx, "/mcchain.referral.Query/PendingRewards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Referral(context.Context, *QueryReferralRequest) (*QueryReferralResponse, error)
	ReferralsByInviter(context.Context, *QueryReferralsByInviterRequest) (*QueryReferralsByInviterResponse, error)
	PendingRewards(context.Context, *QueryPendingRewardsRequest) (*QueryPendingRewardsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Referral(ctx context.Context, req *QueryReferralRequest) (*QueryReferralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Referral not implemented")
}
func (*UnimplementedQueryServer) ReferralsByInviter(ctx context.Context, req *QueryReferralsByInviterRequest) (*QueryReferralsByInviterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReferralsByInviter not implemented")
}
func (*UnimplementedQueryServer) PendingRewards(ctx context.Context, req *QueryPendingRewardsRequest) (*QueryPendingRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingRewards not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Referral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReferralRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Referral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcchain.referral.Query/Referral",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Referral(ctx, req.(*QueryReferralRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ReferralsByInviter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReferralsByInviterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ReferralsByInviter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcchain.referral.Query/ReferralsByInviter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ReferralsByInviter(ctx, req.(*QueryReferralsByInviterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcchain.referral.Query/PendingRewards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingRewards(ctx, req.(*QueryPendingRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mcchain.referral.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Referral",
			Handler:    _Query_Referral_Handler,
		},
		{
			MethodName: "ReferralsByInviter",
			Handler:    _Query_ReferralsByInviter_Handler,
		},
		{
			MethodName: "PendingRewards",
			Handler:    _Query_PendingRewards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mcchain/referral/query.proto",
}

func (m *QueryReferralRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReferralRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReferralRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReferralId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ReferralId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryReferralResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReferralResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReferralResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Referral.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryReferralsByInviterRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReferralsByInviterRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReferralsByInviterRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Inviter) > 0 {
		i -= len(m.Inviter)
		copy(dAtA[i:], m.Inviter)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Inviter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryReferralsByInviterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReferralsByInviterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReferralsByInviterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Referrals) > 0 {
		for iNdEx := len(m.Referrals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Referrals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryPendingRewardsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingRewardsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingRewardsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Claimer) > 0 {
		i -= len(m.Claimer)
		copy(dAtA[i:], m.Claimer)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Claimer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPendingRewardsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingRewardsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingRewardsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Referral) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Referral) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Referral) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x32
	}
	if m.CreatedAt != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x28
	}
	if len(m.InviteCode) > 0 {
		i -= len(m.InviteCode)
		copy(dAtA[i:], m.InviteCode)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.InviteCode)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Invitee) > 0 {
		i -= len(m.Invitee)
		copy(dAtA[i:], m.Invitee)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Invitee)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Inviter) > 0 {
		i -= len(m.Inviter)
		copy(dAtA[i:], m.Inviter)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Inviter)))
		i--
		dAtA[i] = 0x12
	}
	if m.ReferralId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ReferralId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryReferralRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReferralId != 0 {
		n += 1 + sovQuery(uint64(m.ReferralId))
	}
	return n
}

func (m *QueryReferralResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Referral.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryReferralsByInviterRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Inviter)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryReferralsByInviterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Referrals) > 0 {
		for _, e := range m.Referrals {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryPendingRewardsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Claimer)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPendingRewardsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *Referral) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReferralId != 0 {
		n += 1 + sovQuery(uint64(m.ReferralId))
	}
	l = len(m.Inviter)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Invitee)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.InviteCode)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovQuery(uint64(m.CreatedAt))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryReferralRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReferralRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReferralRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferralId", wireType)
			}
			m.ReferralId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReferralId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReferralResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReferralResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReferralResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Referral", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Referral.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReferralsByInviterRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReferralsByInviterRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReferralsByInviterRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inviter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inviter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReferralsByInviterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReferralsByInviterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReferralsByInviterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Referrals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Referrals = append(m.Referrals, Referral{})
			if err := m.Referrals[len(m.Referrals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPendingRewardsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingRewardsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingRewardsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claimer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Claimer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPendingRewardsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingRewardsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingRewardsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Referral) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Referral: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Referral: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferralId", wireType)
			}
			m.ReferralId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReferralId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inviter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inviter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invitee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invitee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InviteCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InviteCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
