// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mcchain/referral/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgCreateReferral is used by an inviter to create a referral link for an invitee.
// Anti-sybil rules are enforced in the message handler:
//   - invitee must already be a registered phonenode (verified via phonenodeKeeper.HasNode)
//   - invitee cannot already be referred by anyone
//   - inviter cannot invite themselves
//   - cooldown_blocks between consecutive referrals from the same inviter
type MsgCreateReferral struct {
	Inviter    string `protobuf:"bytes,1,opt,name=inviter,proto3" json:"inviter,omitempty"`
	Invitee    string `protobuf:"bytes,2,opt,name=invitee,proto3" json:"invitee,omitempty"`
	InviteCode string `protobuf:"bytes,3,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
}

func (m *MsgCreateReferral) Reset()         { *m = MsgCreateReferral{} }
func (m *MsgCreateReferral) String() string { return proto.CompactTextString(m) }
func (*MsgCreateReferral) ProtoMessage()    {}
func (*MsgCreateReferral) Descriptor() ([]byte, []int) {
	return fileDescriptor_975372d61f72699e, []int{0}
}
func (m *MsgCreateReferral) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateReferral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateReferral.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateReferral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateReferral.Merge(m, src)
}
func (m *MsgCreateReferral) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateReferral) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateReferral.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateReferral proto.InternalMessageInfo

func (m *MsgCreateReferral) GetInviter() string {
	if m != nil {
		return m.Inviter
	}
	return ""
}

func (m *MsgCreateReferral) GetInvitee() string {
	if m != nil {
		return m.Invitee
	}
	return ""
}

func (m *MsgCreateReferral) GetInviteCode() string {
	if m != nil {
		return m.InviteCode
	}
	return ""
}

type MsgCreateReferralResponse struct {
	ReferralId uint64 `protobuf:"varint,1,opt,name=referral_id,json=referralId,proto3" json:"referral_id,omitempty"`
}

func (m *MsgCreateReferralResponse) Reset()         { *m = MsgCreateReferralResponse{} }
func (m *MsgCreateReferralResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateReferralResponse) ProtoMessage()    {}
func (*MsgCreateReferralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_975372d61f72699e, []int{1}
}
func (m *MsgCreateReferralResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateReferralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateReferralResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateReferralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateReferralResponse.Merge(m, src)
}
func (m *MsgCreateReferralResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateReferralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateReferralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateReferralResponse proto.InternalMessageInfo

func (m *MsgCreateReferralResponse) GetReferralId() uint64 {
	if m != nil {
		return m.ReferralId
	}
	return 0
}

// MsgClaimReferralReward allows an inviter to claim accumulated referral rewards.
// Rewards are paid from the ecosystem module account, NOT deducted from the invitee.
type MsgClaimReferralReward struct {
	Claimer string `protobuf:"bytes,1,opt,name=claimer,proto3" json:"claimer,omitempty"`
}

func (m *MsgClaimReferralReward) Reset()         { *m = MsgClaimReferralReward{} }
func (m *MsgClaimReferralReward) String() string { return proto.CompactTextString(m) }
func (*MsgClaimReferralReward) ProtoMessage()    {}
func (*MsgClaimReferralReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_975372d61f72699e, []int{2}
}
func (m *MsgClaimReferralReward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimReferralReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimReferralReward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimReferralReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimReferralReward.Merge(m, src)
}
func (m *MsgClaimReferralReward) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimReferralReward) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimReferralReward.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimReferralReward proto.InternalMessageInfo

func (m *MsgClaimReferralReward) GetClaimer() string {
	if m != nil {
		return m.Claimer
	}
	return ""
}

type MsgClaimReferralRewardResponse struct {
	Amount string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgClaimReferralRewardResponse) Reset()         { *m = MsgClaimReferralRewardResponse{} }
func (m *MsgClaimReferralRewardResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimReferralRewardResponse) ProtoMessage()    {}
func (*MsgClaimReferralRewardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_975372d61f72699e, []int{3}
}
func (m *MsgClaimReferralRewardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimReferralRewardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimReferralRewardResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimReferralRewardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimReferralRewardResponse.Merge(m, src)
}
func (m *MsgClaimReferralRewardResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimReferralRewardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimReferralRewardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimReferralRewardResponse proto.InternalMessageInfo

func (m *MsgClaimReferralRewardResponse) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgCreateReferral)(nil), "mcchain.referral.MsgCreateReferral")
	proto.RegisterType((*MsgCreateReferralResponse)(nil), "mcchain.referral.MsgCreateReferralResponse")
	proto.RegisterType((*MsgClaimReferralReward)(nil), "mcchain.referral.MsgClaimReferralReward")
	proto.RegisterType((*MsgClaimReferralRewardResponse)(nil), "mcchain.referral.MsgClaimReferralRewardResponse")
}

func init() { proto.RegisterFile("mcchain/referral/tx.proto", fileDescriptor_975372d61f72699e) }

var fileDescriptor_975372d61f72699e = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcc, 0x4d, 0x4e, 0xce,
	0x48, 0xcc, 0xcc, 0xd3, 0x2f, 0x4a, 0x4d, 0x4b, 0x2d, 0x2a, 0x4a, 0xcc, 0xd1, 0x2f, 0xa9, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x80, 0x4a, 0xe9, 0xc1, 0xa4, 0x94, 0x32, 0xb8, 0x04,
	0x7d, 0x8b, 0xd3, 0x9d, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x83, 0xa0, 0x82, 0x42, 0x12, 0x5c, 0xec,
	0x99, 0x79, 0x65, 0x99, 0x25, 0xa9, 0x45, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0x2e,
	0x42, 0x26, 0x55, 0x82, 0x09, 0x59, 0x26, 0x55, 0x48, 0x9e, 0x8b, 0x1b, 0xc2, 0x8c, 0x4f, 0xce,
	0x4f, 0x49, 0x95, 0x60, 0x06, 0xcb, 0x72, 0x41, 0x84, 0x9c, 0xf3, 0x53, 0x52, 0x95, 0x6c, 0xb8,
	0x24, 0x31, 0x6c, 0x0a, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x06, 0xeb, 0x86, 0x39, 0x29, 0x3e,
	0x33, 0x05, 0x6c, 0x2b, 0x4b, 0x10, 0x17, 0x4c, 0xc8, 0x33, 0x45, 0xc9, 0x88, 0x4b, 0x0c, 0xa4,
	0x3b, 0x27, 0x31, 0x33, 0x17, 0xa1, 0xb9, 0x3c, 0xb1, 0x28, 0x05, 0xe4, 0xa4, 0x64, 0x90, 0x30,
	0xc2, 0xb1, 0x50, 0xae, 0x92, 0x05, 0x97, 0x1c, 0x76, 0x3d, 0x70, 0x6b, 0xc5, 0xb8, 0xd8, 0x12,
	0x73, 0xf3, 0x4b, 0xf3, 0x4a, 0xa0, 0x5a, 0xa1, 0x3c, 0xa3, 0x3b, 0x8c, 0x5c, 0xcc, 0xbe, 0xc5,
	0xe9, 0x42, 0x49, 0x5c, 0x7c, 0x68, 0x41, 0xa3, 0xac, 0x87, 0x1e, 0x84, 0x7a, 0x18, 0xbe, 0x92,
	0xd2, 0x26, 0x42, 0x11, 0xdc, 0x0d, 0x85, 0x5c, 0xc2, 0xd8, 0xbc, 0xa5, 0x81, 0xdd, 0x0c, 0x4c,
	0x95, 0x52, 0x06, 0xc4, 0xaa, 0x84, 0x59, 0xe9, 0x64, 0x74, 0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47,
	0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7, 0x70, 0xe1, 0xb1, 0x1c, 0xc3, 0x8d,
	0xc7, 0x72, 0x0c, 0x51, 0x12, 0xb0, 0xb4, 0x53, 0x81, 0x94, 0x7a, 0x2a, 0x0b, 0x52, 0x8b, 0x93,
	0xd8, 0xc0, 0x29, 0xc8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xee, 0xc4, 0xf5, 0x5e, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateReferral(ctx context.Context, in *MsgCreateReferral, opts ...grpc.CallOption) (*MsgCreateReferralResponse, error)
	ClaimReferralReward(ctx context.Context, in *MsgClaimReferralReward, opts ...grpc.CallOption) (*MsgClaimReferralRewardResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateReferral(ctx context.Context, in *MsgCreateReferral, opts ...grpc.CallOption) (*MsgCreateReferralResponse, error) {
	out := new(MsgCreateReferralResponse)
	err := c.cc.Invoke(ctx, "/mcchain.referral.Msg/CreateReferral", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimReferralReward(ctx context.Context, in *MsgClaimReferralReward, opts ...grpc.CallOption) (*MsgClaimReferralRewardResponse, error) {
	out := new(MsgClaimReferralRewardResponse)
	err := c.cc.Invoke(ctx, "/mcchain.referral.Msg/ClaimReferralReward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateReferral(context.Context, *MsgCreateReferral) (*MsgCreateReferralResponse, error)
	ClaimReferralReward(context.Context, *MsgClaimReferralReward) (*MsgClaimReferralRewardResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateReferral(ctx context.Context, req *MsgCreateReferral) (*MsgCreateReferralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReferral not implemented")
}
func (*UnimplementedMsgServer) ClaimReferralReward(ctx context.Context, req *MsgClaimReferralReward) (*MsgClaimReferralRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimReferralReward not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateReferral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateReferral)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateReferral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcchain.referral.Msg/CreateReferral",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateReferral(ctx, req.(*MsgCreateReferral))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimReferralReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimReferralReward)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimReferralReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcchain.referral.Msg/ClaimReferralReward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimReferralReward(ctx, req.(*MsgClaimReferralReward))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mcchain.referral.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReferral",
			Handler:    _Msg_CreateReferral_Handler,
		},
		{
			MethodName: "ClaimReferralReward",
			Handler:    _Msg_ClaimReferralReward_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mcchain/referral/tx.proto",
}

func (m *MsgCreateReferral) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateReferral) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateReferral) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.InviteCode) > 0 {
		i -= len(m.InviteCode)
		copy(dAtA[i:], m.InviteCode)
		i = encodeVarintTx(dAtA, i, uint64(len(m.InviteCode)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Invitee) > 0 {
		i -= len(m.Invitee)
		copy(dAtA[i:], m.Invitee)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Invitee)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Inviter) > 0 {
		i -= len(m.Inviter)
		copy(dAtA[i:], m.Inviter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Inviter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateReferralResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateReferralResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateReferralResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReferralId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ReferralId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimReferralReward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimReferralReward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimReferralReward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Claimer) > 0 {
		i -= len(m.Claimer)
		copy(dAtA[i:], m.Claimer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Claimer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimReferralRewardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimReferralRewardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimReferralRewardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateReferral) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Inviter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Invitee)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.InviteCode)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateReferralResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReferralId != 0 {
		n += 1 + sovTx(uint64(m.ReferralId))
	}
	return n
}

func (m *MsgClaimReferralReward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Claimer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimReferralRewardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateReferral) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateReferral: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateReferral: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inviter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inviter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invitee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invitee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InviteCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InviteCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateReferralResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateReferralResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateReferralResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferralId", wireType)
			}
			m.ReferralId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReferralId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimReferralReward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimReferralReward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimReferralReward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claimer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Claimer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimReferralRewardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimReferralRewardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimReferralRewardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
