// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mcchain/phonenode/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// attestation_required 是否强制硬件 attestation 才能领取 DePIN 奖励（反女巫）。
	AttestationRequired bool `protobuf:"varint,1,opt,name=attestation_required,json=attestationRequired,proto3" json:"attestation_required,omitempty"`
	// attestation_validity attestation 有效期（秒），过期须重新提交。
	AttestationValidity int64 `protobuf:"varint,2,opt,name=attestation_validity,json=attestationValidity,proto3" json:"attestation_validity,omitempty"`
	// sybil_device_binding 是否将 device_id_hash 1:1 绑定地址（防女巫批量注册）。
	SybilDeviceBinding bool `protobuf:"varint,3,opt,name=sybil_device_binding,json=sybilDeviceBinding,proto3" json:"sybil_device_binding,omitempty"`
	// offline_grace_blocks 离线宽限区块数，超过则触发离线 slash（BeginBlock 检测）。
	OfflineGraceBlocks int64 `protobuf:"varint,4,opt,name=offline_grace_blocks,json=offlineGraceBlocks,proto3" json:"offline_grace_blocks,omitempty"`
	// offline_slash_bps 离线 slash 惩罚基点（万分之 offlined 自质押）。
	OfflineSlashBps uint32 `protobuf:"varint,5,opt,name=offline_slash_bps,json=offlineSlashBps,proto3" json:"offline_slash_bps,omitempty"`
	// contrib_slash_bps 作弊贡献 slash 惩罚基点（链下/争议确认作弊时）。
	ContribSlashBps uint32 `protobuf:"varint,6,opt,name=contrib_slash_bps,json=contribSlashBps,proto3" json:"contrib_slash_bps,omitempty"`
	// attest_slash_bps 伪造 attestation slash 惩罚基点。
	AttestSlashBps uint32 `protobuf:"varint,7,opt,name=attest_slash_bps,json=attestSlashBps,proto3" json:"attest_slash_bps,omitempty"`
	// slash_cooldown_blocks slash 后再认证冷却区块数，默认 43200（~12h @ 4s 出块）。
	SlashCooldownBlocks int64 `protobuf:"varint,8,opt,name=slash_cooldown_blocks,json=slashCooldownBlocks,proto3" json:"slash_cooldown_blocks,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b7eca490b4edbc6, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAttestationRequired() bool {
	if m != nil {
		return m.AttestationRequired
	}
	return false
}

func (m *Params) GetAttestationValidity() int64 {
	if m != nil {
		return m.AttestationValidity
	}
	return 0
}

func (m *Params) GetSybilDeviceBinding() bool {
	if m != nil {
		return m.SybilDeviceBinding
	}
	return false
}

func (m *Params) GetOfflineGraceBlocks() int64 {
	if m != nil {
		return m.OfflineGraceBlocks
	}
	return 0
}

func (m *Params) GetOfflineSlashBps() uint32 {
	if m != nil {
		return m.OfflineSlashBps
	}
	return 0
}

func (m *Params) GetContribSlashBps() uint32 {
	if m != nil {
		return m.ContribSlashBps
	}
	return 0
}

func (m *Params) GetAttestSlashBps() uint32 {
	if m != nil {
		return m.AttestSlashBps
	}
	return 0
}

func (m *Params) GetSlashCooldownBlocks() int64 {
	if m != nil {
		return m.SlashCooldownBlocks
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "mcchain.phonenode.Params")
}

func init() { proto.RegisterFile("mcchain/phonenode/params.proto", fileDescriptor_6b7eca490b4edbc6) }

var fileDescriptor_6b7eca490b4edbc6 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xd1, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x05, 0xe0, 0x98, 0x96, 0x52, 0x59, 0xe2, 0xa7, 0xa1, 0x48, 0x81, 0xc1, 0x54, 0x4c, 0x11,
	0x43, 0x0b, 0x74, 0x63, 0x0c, 0x48, 0xac, 0xa8, 0x48, 0x0c, 0x2c, 0x91, 0x93, 0xb8, 0xa9, 0x45,
	0xea, 0x1b, 0x62, 0x53, 0xe8, 0x4b, 0x20, 0x46, 0x46, 0x1e, 0x87, 0xb1, 0x23, 0x23, 0x6a, 0x5f,
	0x04, 0xc5, 0x76, 0xa3, 0xc0, 0x16, 0xf9, 0x3b, 0x47, 0xbe, 0xf1, 0xc5, 0x64, 0x1a, 0xc7, 0x13,
	0xca, 0xc5, 0x20, 0x9f, 0x80, 0x60, 0x02, 0x12, 0x36, 0xc8, 0x69, 0x41, 0xa7, 0xb2, 0x9f, 0x17,
	0xa0, 0xc0, 0xed, 0x58, 0xef, 0x57, 0x7e, 0xd4, 0x4d, 0x21, 0x05, 0xad, 0x83, 0xf2, 0xcb, 0x04,
	0x4f, 0xde, 0x1a, 0xb8, 0x75, 0xab, 0x9b, 0xee, 0x39, 0xee, 0x52, 0xa5, 0x98, 0x54, 0x54, 0x71,
	0x10, 0x61, 0xc1, 0x9e, 0x9e, 0x79, 0xc1, 0x12, 0x0f, 0xf5, 0x90, 0xdf, 0x1e, 0xed, 0xd7, 0x6c,
	0x64, 0xe9, 0x7f, 0x65, 0x46, 0x33, 0x9e, 0x70, 0x35, 0xf7, 0x36, 0x7a, 0xc8, 0x6f, 0xfc, 0xa9,
	0xdc, 0x5b, 0x72, 0xcf, 0x70, 0x57, 0xce, 0x23, 0x9e, 0x85, 0x09, 0x9b, 0xf1, 0x98, 0x85, 0x11,
	0x17, 0x09, 0x17, 0xa9, 0xd7, 0xd0, 0xb7, 0xb8, 0xda, 0xae, 0x35, 0x05, 0x46, 0xca, 0x06, 0x8c,
	0xc7, 0x19, 0x17, 0x2c, 0x4c, 0x0b, 0x5a, 0x56, 0x32, 0x88, 0x1f, 0xa5, 0xd7, 0xd4, 0x97, 0xb8,
	0xd6, 0x6e, 0x4a, 0x0a, 0xb4, 0xb8, 0xa7, 0xb8, 0xb3, 0x6e, 0xc8, 0x8c, 0xca, 0x49, 0x18, 0xe5,
	0xd2, 0xdb, 0xec, 0x21, 0x7f, 0x7b, 0xb4, 0x6b, 0xe1, 0xae, 0x3c, 0x0f, 0x72, 0x9d, 0x8d, 0x41,
	0xa8, 0x82, 0x47, 0xb5, 0x6c, 0xcb, 0x64, 0x2d, 0x54, 0x59, 0x1f, 0xef, 0x99, 0x5f, 0xaa, 0x45,
	0xb7, 0x74, 0x74, 0xc7, 0x9c, 0x57, 0xc9, 0x0b, 0x7c, 0x60, 0x22, 0x31, 0x40, 0x96, 0xc0, 0x8b,
	0x58, 0x0f, 0xdd, 0x36, 0x2f, 0xa3, 0xf1, 0xca, 0x9a, 0x99, 0xfa, 0xb2, 0xf9, 0xf1, 0x79, 0xec,
	0x04, 0xc3, 0xaf, 0x25, 0x41, 0x8b, 0x25, 0x41, 0x3f, 0x4b, 0x82, 0xde, 0x57, 0xc4, 0x59, 0xac,
	0x88, 0xf3, 0xbd, 0x22, 0xce, 0xc3, 0xe1, 0x7a, 0xe7, 0xaf, 0xb5, 0xad, 0xab, 0x79, 0xce, 0x64,
	0xd4, 0xd2, 0xcb, 0x1c, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x33, 0x43, 0x6c, 0x17, 0x02,
	0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SlashCooldownBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SlashCooldownBlocks))
		i--
		dAtA[i] = 0x40
	}
	if m.AttestSlashBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AttestSlashBps))
		i--
		dAtA[i] = 0x38
	}
	if m.ContribSlashBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ContribSlashBps))
		i--
		dAtA[i] = 0x30
	}
	if m.OfflineSlashBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.OfflineSlashBps))
		i--
		dAtA[i] = 0x28
	}
	if m.OfflineGraceBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.OfflineGraceBlocks))
		i--
		dAtA[i] = 0x20
	}
	if m.SybilDeviceBinding {
		i--
		if m.SybilDeviceBinding {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.AttestationValidity != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AttestationValidity))
		i--
		dAtA[i] = 0x10
	}
	if m.AttestationRequired {
		i--
		if m.AttestationRequired {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AttestationRequired {
		n += 2
	}
	if m.AttestationValidity != 0 {
		n += 1 + sovParams(uint64(m.AttestationValidity))
	}
	if m.SybilDeviceBinding {
		n += 2
	}
	if m.OfflineGraceBlocks != 0 {
		n += 1 + sovParams(uint64(m.OfflineGraceBlocks))
	}
	if m.OfflineSlashBps != 0 {
		n += 1 + sovParams(uint64(m.OfflineSlashBps))
	}
	if m.ContribSlashBps != 0 {
		n += 1 + sovParams(uint64(m.ContribSlashBps))
	}
	if m.AttestSlashBps != 0 {
		n += 1 + sovParams(uint64(m.AttestSlashBps))
	}
	if m.SlashCooldownBlocks != 0 {
		n += 1 + sovParams(uint64(m.SlashCooldownBlocks))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationRequired", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AttestationRequired = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationValidity", wireType)
			}
			m.AttestationValidity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AttestationValidity |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SybilDeviceBinding", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SybilDeviceBinding = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OfflineGraceBlocks", wireType)
			}
			m.OfflineGraceBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OfflineGraceBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OfflineSlashBps", wireType)
			}
			m.OfflineSlashBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OfflineSlashBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContribSlashBps", wireType)
			}
			m.ContribSlashBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContribSlashBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestSlashBps", wireType)
			}
			m.AttestSlashBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AttestSlashBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashCooldownBlocks", wireType)
			}
			m.SlashCooldownBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlashCooldownBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
