// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mcchain/dex/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// StateKV 模块 KVStore 的一条原始快照记录（导出/导入专用）。
type StateKV struct {
	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *StateKV) Reset()         { *m = StateKV{} }
func (m *StateKV) String() string { return proto.CompactTextString(m) }
func (*StateKV) ProtoMessage()    {}
func (*StateKV) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d41522b1755ec93, []int{0}
}
func (m *StateKV) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StateKV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StateKV.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StateKV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateKV.Merge(m, src)
}
func (m *StateKV) XXX_Size() int {
	return m.Size()
}
func (m *StateKV) XXX_DiscardUnknown() {
	xxx_messageInfo_StateKV.DiscardUnknown(m)
}

var xxx_messageInfo_StateKV proto.InternalMessageInfo

func (m *StateKV) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *StateKV) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type GenesisState struct {
	Pools      []Pool `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools"`
	NextPoolId uint64 `protobuf:"varint,2,opt,name=next_pool_id,json=nextPoolId,proto3" json:"next_pool_id,omitempty"`
	Params     Params `protobuf:"bytes,3,opt,name=params,proto3" json:"params"`
	// state_kv 模块运行期状态的完整原始快照。
	//
	// 导出若只写 pools / next_pool_id / params 会遗漏结算配置
	// （SettlementConfig：Authority + Halted）与 LP 锁仓记录（LiquidityLock）：
	// 导入后结算闸门会被重新置为 Halted=true（通道重新熔断），LP 锁仓记录丢失
	// 导致锁定期形同虚设。快照机制让这两类状态随导出一起往返。
	StateKv []StateKV `protobuf:"bytes,4,rep,name=state_kv,json=stateKv,proto3" json:"state_kv"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d41522b1755ec93, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetPools() []Pool {
	if m != nil {
		return m.Pools
	}
	return nil
}

func (m *GenesisState) GetNextPoolId() uint64 {
	if m != nil {
		return m.NextPoolId
	}
	return 0
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetStateKv() []StateKV {
	if m != nil {
		return m.StateKv
	}
	return nil
}

type Params struct {
	DefaultFeeRateBps    uint32 `protobuf:"varint,1,opt,name=default_fee_rate_bps,json=defaultFeeRateBps,proto3" json:"default_fee_rate_bps,omitempty"`
	MaxPools             uint64 `protobuf:"varint,2,opt,name=max_pools,json=maxPools,proto3" json:"max_pools,omitempty"`
	LpIncentivePerDay    string `protobuf:"bytes,3,opt,name=lp_incentive_per_day,json=lpIncentivePerDay,proto3" json:"lp_incentive_per_day,omitempty"`
	LpIncentiveEndHeight uint64 `protobuf:"varint,4,opt,name=lp_incentive_end_height,json=lpIncentiveEndHeight,proto3" json:"lp_incentive_end_height,omitempty"`
	LpLockBlocks         uint64 `protobuf:"varint,5,opt,name=lp_lock_blocks,json=lpLockBlocks,proto3" json:"lp_lock_blocks,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d41522b1755ec93, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDefaultFeeRateBps() uint32 {
	if m != nil {
		return m.DefaultFeeRateBps
	}
	return 0
}

func (m *Params) GetMaxPools() uint64 {
	if m != nil {
		return m.MaxPools
	}
	return 0
}

func (m *Params) GetLpIncentivePerDay() string {
	if m != nil {
		return m.LpIncentivePerDay
	}
	return ""
}

func (m *Params) GetLpIncentiveEndHeight() uint64 {
	if m != nil {
		return m.LpIncentiveEndHeight
	}
	return 0
}

func (m *Params) GetLpLockBlocks() uint64 {
	if m != nil {
		return m.LpLockBlocks
	}
	return 0
}

func init() {
	proto.RegisterType((*StateKV)(nil), "mcchain.dex.StateKV")
	proto.RegisterType((*GenesisState)(nil), "mcchain.dex.GenesisState")
	proto.RegisterType((*Params)(nil), "mcchain.dex.Params")
}

func init() { proto.RegisterFile("mcchain/dex/genesis.proto", fileDescriptor_0d41522b1755ec93) }

var fileDescriptor_0d41522b1755ec93 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x52, 0x4d, 0x6b, 0xdb, 0x30,
	0x18, 0x8e, 0x96, 0x8f, 0xb6, 0x4a, 0x36, 0x16, 0xd5, 0x6c, 0x5e, 0x07, 0x5e, 0x08, 0x3b, 0xe4,
	0xd2, 0x98, 0x76, 0xf4, 0x0f, 0x84, 0x7d, 0x95, 0xee, 0x10, 0x3c, 0xd8, 0x61, 0x17, 0xa1, 0xd8,
	0x6f, 0x13, 0x13, 0xc5, 0x12, 0x96, 0x1a, 0x9c, 0x7f, 0xb1, 0x9f, 0xd5, 0xdd, 0x7a, 0xdc, 0x69,
	0x8c, 0x64, 0x3f, 0xa4, 0xe8, 0x95, 0x0b, 0xc9, 0xc5, 0x48, 0xcf, 0x97, 0xdf, 0x47, 0xbc, 0xf4,
	0xcd, 0x2a, 0x4d, 0x17, 0x22, 0x2f, 0xe2, 0x0c, 0xaa, 0x78, 0x0e, 0x05, 0x98, 0xdc, 0x8c, 0x75,
	0xa9, 0xac, 0x62, 0xdd, 0x9a, 0x1a, 0x67, 0x50, 0x9d, 0x05, 0x73, 0x35, 0x57, 0x88, 0xc7, 0xee,
	0xe4, 0x25, 0x67, 0xaf, 0xf6, 0xdd, 0x5a, 0x29, 0xe9, 0xf1, 0xe1, 0x05, 0x3d, 0xfa, 0x6e, 0x85,
	0x85, 0x9b, 0x1f, 0xec, 0x25, 0x6d, 0x2e, 0x61, 0x13, 0x92, 0x01, 0x19, 0xf5, 0x12, 0x77, 0x64,
	0x01, 0x6d, 0xaf, 0x85, 0xbc, 0x83, 0xf0, 0x19, 0x62, 0xfe, 0x32, 0xfc, 0x4d, 0x68, 0xef, 0x8b,
	0xff, 0x3f, 0x5a, 0xd9, 0x39, 0x6d, 0xbb, 0x44, 0x13, 0x92, 0x41, 0x73, 0xd4, 0xbd, 0xec, 0x8f,
	0xf7, 0xc6, 0x19, 0x4f, 0x95, 0x92, 0x93, 0xd6, 0xfd, 0xdf, 0x77, 0x8d, 0xc4, 0xab, 0xd8, 0x80,
	0xf6, 0x0a, 0xa8, 0x2c, 0x77, 0x37, 0x9e, 0x67, 0x18, 0xde, 0x4a, 0xa8, 0xc3, 0x9c, 0xf8, 0x3a,
	0x63, 0x17, 0xb4, 0xa3, 0x45, 0x29, 0x56, 0x26, 0x6c, 0x0e, 0xc8, 0xa8, 0x7b, 0x79, 0x7a, 0x98,
	0x88, 0x54, 0x9d, 0x59, 0x0b, 0xd9, 0x15, 0x3d, 0x36, 0x6e, 0x18, 0xbe, 0x5c, 0x87, 0x2d, 0x1c,
	0x23, 0x38, 0x30, 0xd5, 0x25, 0x6b, 0xd7, 0x11, 0x6a, 0x6f, 0xd6, 0xc3, 0xff, 0x84, 0x76, 0x7c,
	0x1e, 0x8b, 0x69, 0x90, 0xc1, 0xad, 0xb8, 0x93, 0x96, 0xdf, 0x02, 0xf0, 0xd2, 0x85, 0xcd, 0xb4,
	0xc1, 0xf7, 0x78, 0x9e, 0xf4, 0x6b, 0xee, 0x33, 0x40, 0x22, 0x2c, 0x4c, 0xb4, 0x61, 0x6f, 0xe9,
	0xc9, 0x4a, 0x54, 0xdc, 0x57, 0xf7, 0x25, 0x8e, 0x57, 0xa2, 0x9a, 0x62, 0xc9, 0x98, 0x06, 0x52,
	0xf3, 0xbc, 0x48, 0xa1, 0xb0, 0xf9, 0x1a, 0xb8, 0x86, 0x92, 0x67, 0x62, 0x83, 0x85, 0x4e, 0x92,
	0xbe, 0xd4, 0xd7, 0x4f, 0xd4, 0x14, 0xca, 0x8f, 0x62, 0xc3, 0xae, 0xe8, 0xeb, 0x03, 0x03, 0x14,
	0x19, 0x5f, 0x40, 0x3e, 0x5f, 0xd8, 0xb0, 0x85, 0xd9, 0xc1, 0x9e, 0xe7, 0x53, 0x91, 0x7d, 0x45,
	0x8e, 0xbd, 0xa7, 0x2f, 0xa4, 0xe6, 0x52, 0xa5, 0x4b, 0x3e, 0x73, 0x5f, 0x13, 0xb6, 0x51, 0xdd,
	0x93, 0xfa, 0x9b, 0x4a, 0x97, 0x13, 0xc4, 0x26, 0xe7, 0xf7, 0xdb, 0x88, 0x3c, 0x6c, 0x23, 0xf2,
	0x6f, 0x1b, 0x91, 0x5f, 0xbb, 0xa8, 0xf1, 0xb0, 0x8b, 0x1a, 0x7f, 0x76, 0x51, 0xe3, 0xe7, 0xe9,
	0xd3, 0x5e, 0x54, 0xb8, 0x19, 0x76, 0xa3, 0xc1, 0xcc, 0x3a, 0xb8, 0x1b, 0x1f, 0x1e, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x94, 0x5b, 0x54, 0xc4, 0x73, 0x02, 0x00, 0x00,
}

func (m *StateKV) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StateKV) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StateKV) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StateKv) > 0 {
		for iNdEx := len(m.StateKv) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StateKv[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.NextPoolId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextPoolId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Pools) > 0 {
		for iNdEx := len(m.Pools) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pools[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LpLockBlocks != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LpLockBlocks))
		i--
		dAtA[i] = 0x28
	}
	if m.LpIncentiveEndHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LpIncentiveEndHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.LpIncentivePerDay) > 0 {
		i -= len(m.LpIncentivePerDay)
		copy(dAtA[i:], m.LpIncentivePerDay)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.LpIncentivePerDay)))
		i--
		dAtA[i] = 0x1a
	}
	if m.MaxPools != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxPools))
		i--
		dAtA[i] = 0x10
	}
	if m.DefaultFeeRateBps != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DefaultFeeRateBps))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StateKV) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Pools) > 0 {
		for _, e := range m.Pools {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NextPoolId != 0 {
		n += 1 + sovGenesis(uint64(m.NextPoolId))
	}
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.StateKv) > 0 {
		for _, e := range m.StateKv {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DefaultFeeRateBps != 0 {
		n += 1 + sovGenesis(uint64(m.DefaultFeeRateBps))
	}
	if m.MaxPools != 0 {
		n += 1 + sovGenesis(uint64(m.MaxPools))
	}
	l = len(m.LpIncentivePerDay)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.LpIncentiveEndHeight != 0 {
		n += 1 + sovGenesis(uint64(m.LpIncentiveEndHeight))
	}
	if m.LpLockBlocks != 0 {
		n += 1 + sovGenesis(uint64(m.LpLockBlocks))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StateKV) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StateKV: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StateKV: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = append(m.Value[:0], dAtA[iNdEx:postIndex]...)
			if m.Value == nil {
				m.Value = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pools", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pools = append(m.Pools, Pool{})
			if err := m.Pools[len(m.Pools)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextPoolId", wireType)
			}
			m.NextPoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextPoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateKv", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateKv = append(m.StateKv, StateKV{})
			if err := m.StateKv[len(m.StateKv)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultFeeRateBps", wireType)
			}
			m.DefaultFeeRateBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultFeeRateBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPools", wireType)
			}
			m.MaxPools = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPools |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LpIncentivePerDay", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LpIncentivePerDay = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LpIncentiveEndHeight", wireType)
			}
			m.LpIncentiveEndHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LpIncentiveEndHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LpLockBlocks", wireType)
			}
			m.LpLockBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LpLockBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
