// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mcchain/dex/pool.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Pool struct {
	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DenomA     string `protobuf:"bytes,2,opt,name=denom_a,json=denomA,proto3" json:"denom_a,omitempty"`
	DenomB     string `protobuf:"bytes,3,opt,name=denom_b,json=denomB,proto3" json:"denom_b,omitempty"`
	ReserveA   string `protobuf:"bytes,4,opt,name=reserve_a,json=reserveA,proto3" json:"reserve_a,omitempty"`
	ReserveB   string `protobuf:"bytes,5,opt,name=reserve_b,json=reserveB,proto3" json:"reserve_b,omitempty"`
	TotalLp    string `protobuf:"bytes,6,opt,name=total_lp,json=totalLp,proto3" json:"total_lp,omitempty"`
	FeeRateBps uint32 `protobuf:"varint,7,opt,name=fee_rate_bps,json=feeRateBps,proto3" json:"fee_rate_bps,omitempty"`
	Owner      string `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *Pool) Reset()         { *m = Pool{} }
func (m *Pool) String() string { return proto.CompactTextString(m) }
func (*Pool) ProtoMessage()    {}
func (*Pool) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f0a03f47867f1c, []int{0}
}
func (m *Pool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Pool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Pool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Pool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pool.Merge(m, src)
}
func (m *Pool) XXX_Size() int {
	return m.Size()
}
func (m *Pool) XXX_DiscardUnknown() {
	xxx_messageInfo_Pool.DiscardUnknown(m)
}

var xxx_messageInfo_Pool proto.InternalMessageInfo

func (m *Pool) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pool) GetDenomA() string {
	if m != nil {
		return m.DenomA
	}
	return ""
}

func (m *Pool) GetDenomB() string {
	if m != nil {
		return m.DenomB
	}
	return ""
}

func (m *Pool) GetReserveA() string {
	if m != nil {
		return m.ReserveA
	}
	return ""
}

func (m *Pool) GetReserveB() string {
	if m != nil {
		return m.ReserveB
	}
	return ""
}

func (m *Pool) GetTotalLp() string {
	if m != nil {
		return m.TotalLp
	}
	return ""
}

func (m *Pool) GetFeeRateBps() uint32 {
	if m != nil {
		return m.FeeRateBps
	}
	return 0
}

func (m *Pool) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type LiquidityLock struct {
	LpAddress    string `protobuf:"bytes,1,opt,name=lp_address,json=lpAddress,proto3" json:"lp_address,omitempty"`
	PoolId       uint64 `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	LockHeight   uint64 `protobuf:"varint,3,opt,name=lock_height,json=lockHeight,proto3" json:"lock_height,omitempty"`
	UnlockHeight uint64 `protobuf:"varint,4,opt,name=unlock_height,json=unlockHeight,proto3" json:"unlock_height,omitempty"`
	LpAmount     string `protobuf:"bytes,5,opt,name=lp_amount,json=lpAmount,proto3" json:"lp_amount,omitempty"`
}

func (m *LiquidityLock) Reset()         { *m = LiquidityLock{} }
func (m *LiquidityLock) String() string { return proto.CompactTextString(m) }
func (*LiquidityLock) ProtoMessage()    {}
func (*LiquidityLock) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f0a03f47867f1c, []int{1}
}
func (m *LiquidityLock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidityLock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidityLock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidityLock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidityLock.Merge(m, src)
}
func (m *LiquidityLock) XXX_Size() int {
	return m.Size()
}
func (m *LiquidityLock) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidityLock.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidityLock proto.InternalMessageInfo

func (m *LiquidityLock) GetLpAddress() string {
	if m != nil {
		return m.LpAddress
	}
	return ""
}

func (m *LiquidityLock) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *LiquidityLock) GetLockHeight() uint64 {
	if m != nil {
		return m.LockHeight
	}
	return 0
}

func (m *LiquidityLock) GetUnlockHeight() uint64 {
	if m != nil {
		return m.UnlockHeight
	}
	return 0
}

func (m *LiquidityLock) GetLpAmount() string {
	if m != nil {
		return m.LpAmount
	}
	return ""
}

func init() {
	proto.RegisterType((*Pool)(nil), "mcchain.dex.Pool")
	proto.RegisterType((*LiquidityLock)(nil), "mcchain.dex.LiquidityLock")
}

func init() { proto.RegisterFile("mcchain/dex/pool.proto", fileDescriptor_36f0a03f47867f1c) }

var fileDescriptor_36f0a03f47867f1c = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x31, 0x8e, 0xda, 0x40,
	0x14, 0x86, 0x19, 0x62, 0x0c, 0x7e, 0x40, 0x8a, 0x49, 0x94, 0x4c, 0x84, 0xe2, 0x58, 0xa4, 0xa1,
	0x09, 0x14, 0x39, 0x81, 0x5d, 0x25, 0x12, 0x45, 0xe4, 0x32, 0xcd, 0xc8, 0xf6, 0x3c, 0xc2, 0x88,
	0xc1, 0x33, 0xb1, 0x87, 0x5d, 0xb8, 0xc5, 0x9e, 0x63, 0x4f, 0xb2, 0x25, 0xcd, 0x4a, 0x5b, 0xae,
	0xe0, 0x22, 0x2b, 0x0f, 0xa0, 0x65, 0xcb, 0xff, 0xfb, 0x9e, 0x65, 0xfd, 0xf3, 0xc3, 0xa7, 0x75,
	0x51, 0x2c, 0x33, 0x59, 0xce, 0x04, 0x6e, 0x67, 0x46, 0x6b, 0x35, 0x35, 0x95, 0xb6, 0x9a, 0xf6,
	0xcf, 0x7c, 0x2a, 0x70, 0x3b, 0x7e, 0x24, 0xe0, 0xfd, 0xd1, 0x5a, 0xd1, 0xf7, 0xd0, 0x96, 0x82,
	0x91, 0x88, 0x4c, 0xbc, 0xb4, 0x2d, 0x05, 0xfd, 0x0c, 0x5d, 0x81, 0xa5, 0x5e, 0xf3, 0x8c, 0xb5,
	0x23, 0x32, 0x09, 0x52, 0xdf, 0xc5, 0xf8, 0x55, 0xe4, 0xec, 0xdd, 0x95, 0x48, 0xe8, 0x08, 0x82,
	0x0a, 0x6b, 0xac, 0x6e, 0x90, 0x67, 0xcc, 0x73, 0xaa, 0x77, 0x06, 0xf1, 0xb5, 0xcc, 0x59, 0xe7,
	0x8d, 0x4c, 0xe8, 0x17, 0xe8, 0x59, 0x6d, 0x33, 0xc5, 0x95, 0x61, 0xbe, 0x73, 0x5d, 0x97, 0xe7,
	0x86, 0x46, 0x30, 0x58, 0x20, 0xf2, 0x2a, 0xb3, 0xc8, 0x73, 0x53, 0xb3, 0x6e, 0x44, 0x26, 0xc3,
	0x14, 0x16, 0x88, 0x69, 0x66, 0x31, 0x31, 0x35, 0xfd, 0x08, 0x1d, 0x7d, 0x5b, 0x62, 0xc5, 0x7a,
	0xee, 0xcb, 0x53, 0x18, 0xdf, 0x13, 0x18, 0xce, 0xe5, 0xff, 0x8d, 0x14, 0xd2, 0xee, 0xe6, 0xba,
	0x58, 0xd1, 0xaf, 0x00, 0xca, 0xf0, 0x4c, 0x88, 0x0a, 0xeb, 0xda, 0x15, 0x0d, 0xd2, 0x40, 0x99,
	0xf8, 0x04, 0x9a, 0x5a, 0xcd, 0x1b, 0x71, 0x29, 0x5c, 0x5f, 0x2f, 0xf5, 0x9b, 0xf8, 0x5b, 0xd0,
	0x6f, 0xd0, 0x57, 0xba, 0x58, 0xf1, 0x25, 0xca, 0x7f, 0x4b, 0xeb, 0x3a, 0x7b, 0x29, 0x34, 0xe8,
	0x97, 0x23, 0xf4, 0x3b, 0x0c, 0x37, 0xe5, 0xf5, 0x89, 0xe7, 0x4e, 0x06, 0x27, 0x78, 0x3e, 0x1a,
	0x41, 0xd0, 0xfc, 0x7d, 0xad, 0x37, 0xa5, 0xbd, 0xf4, 0x57, 0x26, 0x76, 0x39, 0xf9, 0xf1, 0x70,
	0x08, 0xc9, 0xfe, 0x10, 0x92, 0xe7, 0x43, 0x48, 0xee, 0x8e, 0x61, 0x6b, 0x7f, 0x0c, 0x5b, 0x4f,
	0xc7, 0xb0, 0xf5, 0xf7, 0xc3, 0x65, 0xc3, 0xad, 0x5b, 0xd1, 0xee, 0x0c, 0xd6, 0xb9, 0xef, 0x76,
	0xfc, 0xf9, 0x12, 0x00, 0x00, 0xff, 0xff, 0x54, 0x0c, 0x2a, 0x15, 0xe1, 0x01, 0x00, 0x00,
}

func (m *Pool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Pool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Pool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintPool(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x42
	}
	if m.FeeRateBps != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.FeeRateBps))
		i--
		dAtA[i] = 0x38
	}
	if len(m.TotalLp) > 0 {
		i -= len(m.TotalLp)
		copy(dAtA[i:], m.TotalLp)
		i = encodeVarintPool(dAtA, i, uint64(len(m.TotalLp)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ReserveB) > 0 {
		i -= len(m.ReserveB)
		copy(dAtA[i:], m.ReserveB)
		i = encodeVarintPool(dAtA, i, uint64(len(m.ReserveB)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ReserveA) > 0 {
		i -= len(m.ReserveA)
		copy(dAtA[i:], m.ReserveA)
		i = encodeVarintPool(dAtA, i, uint64(len(m.ReserveA)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DenomB) > 0 {
		i -= len(m.DenomB)
		copy(dAtA[i:], m.DenomB)
		i = encodeVarintPool(dAtA, i, uint64(len(m.DenomB)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DenomA) > 0 {
		i -= len(m.DenomA)
		copy(dAtA[i:], m.DenomA)
		i = encodeVarintPool(dAtA, i, uint64(len(m.DenomA)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LiquidityLock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidityLock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidityLock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LpAmount) > 0 {
		i -= len(m.LpAmount)
		copy(dAtA[i:], m.LpAmount)
		i = encodeVarintPool(dAtA, i, uint64(len(m.LpAmount)))
		i--
		dAtA[i] = 0x2a
	}
	if m.UnlockHeight != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.UnlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.LockHeight != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.LockHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.PoolId != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.LpAddress) > 0 {
		i -= len(m.LpAddress)
		copy(dAtA[i:], m.LpAddress)
		i = encodeVarintPool(dAtA, i, uint64(len(m.LpAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPool(dAtA []byte, offset int, v uint64) int {
	offset -= sovPool(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Pool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovPool(uint64(m.Id))
	}
	l = len(m.DenomA)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	l = len(m.DenomB)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	l = len(m.ReserveA)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	l = len(m.ReserveB)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	l = len(m.TotalLp)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	if m.FeeRateBps != 0 {
		n += 1 + sovPool(uint64(m.FeeRateBps))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	return n
}

func (m *LiquidityLock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LpAddress)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	if m.PoolId != 0 {
		n += 1 + sovPool(uint64(m.PoolId))
	}
	if m.LockHeight != 0 {
		n += 1 + sovPool(uint64(m.LockHeight))
	}
	if m.UnlockHeight != 0 {
		n += 1 + sovPool(uint64(m.UnlockHeight))
	}
	l = len(m.LpAmount)
	if l > 0 {
		n += 1 + l + sovPool(uint64(l))
	}
	return n
}

func sovPool(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPool(x uint64) (n int) {
	return sovPool(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Pool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Pool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Pool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomA", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomA = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomB", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomB = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveA", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReserveA = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveB", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReserveB = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalLp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalLp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeRateBps", wireType)
			}
			m.FeeRateBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeRateBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LiquidityLock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidityLock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidityLock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LpAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LpAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockHeight", wireType)
			}
			m.LockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnlockHeight", wireType)
			}
			m.UnlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LpAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LpAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPool(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPool
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPool
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPool
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPool
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPool        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPool          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPool = fmt.Errorf("proto: unexpected end of group")
)
