// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mcchain/mcchain/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgInitiateHandover opens a progressive governance handover. The signer must
// be the current governance authority.
type MsgInitiateHandover struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// new_governor is the address that holds governance after the timelock.
	NewGovernor string `protobuf:"bytes,2,opt,name=new_governor,json=newGovernor,proto3" json:"new_governor,omitempty"`
}

func (m *MsgInitiateHandover) Reset()         { *m = MsgInitiateHandover{} }
func (m *MsgInitiateHandover) String() string { return proto.CompactTextString(m) }
func (*MsgInitiateHandover) ProtoMessage()    {}
func (*MsgInitiateHandover) Descriptor() ([]byte, []int) {
	return fileDescriptor_5720c3743a21f2c6, []int{0}
}
func (m *MsgInitiateHandover) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitiateHandover) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitiateHandover.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitiateHandover) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitiateHandover.Merge(m, src)
}
func (m *MsgInitiateHandover) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitiateHandover) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitiateHandover.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitiateHandover proto.InternalMessageInfo

func (m *MsgInitiateHandover) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgInitiateHandover) GetNewGovernor() string {
	if m != nil {
		return m.NewGovernor
	}
	return ""
}

type MsgInitiateHandoverResponse struct {
	// activation_height is the first height at which the transfer may execute.
	ActivationHeight int64 `protobuf:"varint,1,opt,name=activation_height,json=activationHeight,proto3" json:"activation_height,omitempty"`
}

func (m *MsgInitiateHandoverResponse) Reset()         { *m = MsgInitiateHandoverResponse{} }
func (m *MsgInitiateHandoverResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInitiateHandoverResponse) ProtoMessage()    {}
func (*MsgInitiateHandoverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5720c3743a21f2c6, []int{1}
}
func (m *MsgInitiateHandoverResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitiateHandoverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitiateHandoverResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitiateHandoverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitiateHandoverResponse.Merge(m, src)
}
func (m *MsgInitiateHandoverResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitiateHandoverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitiateHandoverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitiateHandoverResponse proto.InternalMessageInfo

func (m *MsgInitiateHandoverResponse) GetActivationHeight() int64 {
	if m != nil {
		return m.ActivationHeight
	}
	return 0
}

// MsgCompleteHandover finalises a pending handover. It succeeds only after the
// activation height, and only once.
type MsgCompleteHandover struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
}

func (m *MsgCompleteHandover) Reset()         { *m = MsgCompleteHandover{} }
func (m *MsgCompleteHandover) String() string { return proto.CompactTextString(m) }
func (*MsgCompleteHandover) ProtoMessage()    {}
func (*MsgCompleteHandover) Descriptor() ([]byte, []int) {
	return fileDescriptor_5720c3743a21f2c6, []int{2}
}
func (m *MsgCompleteHandover) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCompleteHandover) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCompleteHandover.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCompleteHandover) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCompleteHandover.Merge(m, src)
}
func (m *MsgCompleteHandover) XXX_Size() int {
	return m.Size()
}
func (m *MsgCompleteHandover) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCompleteHandover.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCompleteHandover proto.InternalMessageInfo

func (m *MsgCompleteHandover) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

type MsgCompleteHandoverResponse struct {
	NewGovernor string `protobuf:"bytes,1,opt,name=new_governor,json=newGovernor,proto3" json:"new_governor,omitempty"`
}

func (m *MsgCompleteHandoverResponse) Reset()         { *m = MsgCompleteHandoverResponse{} }
func (m *MsgCompleteHandoverResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCompleteHandoverResponse) ProtoMessage()    {}
func (*MsgCompleteHandoverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5720c3743a21f2c6, []int{3}
}
func (m *MsgCompleteHandoverResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCompleteHandoverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCompleteHandoverResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCompleteHandoverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCompleteHandoverResponse.Merge(m, src)
}
func (m *MsgCompleteHandoverResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCompleteHandoverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCompleteHandoverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCompleteHandoverResponse proto.InternalMessageInfo

func (m *MsgCompleteHandoverResponse) GetNewGovernor() string {
	if m != nil {
		return m.NewGovernor
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgInitiateHandover)(nil), "mcchain.mcchain.MsgInitiateHandover")
	proto.RegisterType((*MsgInitiateHandoverResponse)(nil), "mcchain.mcchain.MsgInitiateHandoverResponse")
	proto.RegisterType((*MsgCompleteHandover)(nil), "mcchain.mcchain.MsgCompleteHandover")
	proto.RegisterType((*MsgCompleteHandoverResponse)(nil), "mcchain.mcchain.MsgCompleteHandoverResponse")
}

func init() { proto.RegisterFile("mcchain/mcchain/tx.proto", fileDescriptor_5720c3743a21f2c6) }

var fileDescriptor_5720c3743a21f2c6 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc8, 0x4d, 0x4e, 0xce,
	0x48, 0xcc, 0xcc, 0xd3, 0x87, 0xd1, 0x25, 0x15, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xfc,
	0x50, 0x11, 0x3d, 0x28, 0xad, 0x14, 0xc6, 0x25, 0xec, 0x5b, 0x9c, 0xee, 0x99, 0x97, 0x59, 0x92,
	0x99, 0x58, 0x92, 0xea, 0x91, 0x98, 0x97, 0x92, 0x5f, 0x96, 0x5a, 0x24, 0x24, 0xc3, 0xc5, 0x99,
	0x58, 0x5a, 0x92, 0x91, 0x5f, 0x94, 0x59, 0x52, 0x29, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x84,
	0x10, 0x10, 0x52, 0xe4, 0xe2, 0xc9, 0x4b, 0x2d, 0x8f, 0x4f, 0x07, 0x29, 0xcd, 0xcb, 0x2f, 0x92,
	0x60, 0x02, 0x2b, 0xe0, 0xce, 0x4b, 0x2d, 0x77, 0x87, 0x0a, 0x29, 0x79, 0x71, 0x49, 0x63, 0x31,
	0x37, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x9b, 0x4b, 0x30, 0x31, 0xb9, 0x24,
	0xb3, 0x2c, 0xb1, 0x24, 0x33, 0x3f, 0x2f, 0x3e, 0x23, 0x35, 0x33, 0x3d, 0xa3, 0x04, 0x6c, 0x0f,
	0x73, 0x90, 0x00, 0x42, 0xc2, 0x03, 0x2c, 0xae, 0x64, 0x0c, 0x76, 0xa3, 0x73, 0x7e, 0x6e, 0x41,
	0x4e, 0x2a, 0xb1, 0x6e, 0x54, 0x72, 0x00, 0x3b, 0x00, 0x5d, 0x13, 0xdc, 0x01, 0xe8, 0x5e, 0x60,
	0xc4, 0xf0, 0x82, 0xd1, 0x55, 0x46, 0x2e, 0x66, 0xdf, 0xe2, 0x74, 0xa1, 0x34, 0x2e, 0x01, 0x8c,
	0xf0, 0x51, 0xd1, 0x43, 0x0b, 0x48, 0x3d, 0x2c, 0xbe, 0x95, 0xd2, 0x21, 0x46, 0x15, 0xdc, 0x49,
	0x69, 0x5c, 0x02, 0x18, 0x7e, 0xc4, 0x6a, 0x0f, 0xba, 0x2a, 0xec, 0xf6, 0xe0, 0xf2, 0xba, 0x93,
	0xe1, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1,
	0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0x89, 0xc3, 0xd2, 0x4b, 0x05,
	0x22, 0xe5, 0x54, 0x16, 0xa4, 0x16, 0x27, 0xb1, 0x81, 0x53, 0x8f, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x7f, 0x3a, 0xf0, 0x39, 0x59, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// InitiateHandover registers the incoming governor and starts the timelock.
	InitiateHandover(ctx context.Context, in *MsgInitiateHandover, opts ...grpc.CallOption) (*MsgInitiateHandoverResponse, error)
	// CompleteHandover executes the transfer once the timelock has elapsed.
	CompleteHandover(ctx context.Context, in *MsgCompleteHandover, opts ...grpc.CallOption) (*MsgCompleteHandoverResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) InitiateHandover(ctx context.Context, in *MsgInitiateHandover, opts ...grpc.CallOption) (*MsgInitiateHandoverResponse, error) {
	out := new(MsgInitiateHandoverResponse)
	err := c.cc.Invoke(ctx, "/mcchain.mcchain.Msg/InitiateHandover", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CompleteHandover(ctx context.Context, in *MsgCompleteHandover, opts ...grpc.CallOption) (*MsgCompleteHandoverResponse, error) {
	out := new(MsgCompleteHandoverResponse)
	err := c.cc.Invoke(ctx, "/mcchain.mcchain.Msg/CompleteHandover", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// InitiateHandover registers the incoming governor and starts the timelock.
	InitiateHandover(context.Context, *MsgInitiateHandover) (*MsgInitiateHandoverResponse, error)
	// CompleteHandover executes the transfer once the timelock has elapsed.
	CompleteHandover(context.Context, *MsgCompleteHandover) (*MsgCompleteHandoverResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) InitiateHandover(ctx context.Context, req *MsgInitiateHandover) (*MsgInitiateHandoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateHandover not implemented")
}
func (*UnimplementedMsgServer) CompleteHandover(ctx context.Context, req *MsgCompleteHandover) (*MsgCompleteHandoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteHandover not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_InitiateHandover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInitiateHandover)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InitiateHandover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcchain.mcchain.Msg/InitiateHandover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InitiateHandover(ctx, req.(*MsgInitiateHandover))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CompleteHandover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCompleteHandover)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CompleteHandover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcchain.mcchain.Msg/CompleteHandover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CompleteHandover(ctx, req.(*MsgCompleteHandover))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mcchain.mcchain.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateHandover",
			Handler:    _Msg_InitiateHandover_Handler,
		},
		{
			MethodName: "CompleteHandover",
			Handler:    _Msg_CompleteHandover_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mcchain/mcchain/tx.proto",
}

func (m *MsgInitiateHandover) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitiateHandover) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitiateHandover) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewGovernor) > 0 {
		i -= len(m.NewGovernor)
		copy(dAtA[i:], m.NewGovernor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewGovernor)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInitiateHandoverResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitiateHandoverResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitiateHandoverResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ActivationHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ActivationHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgCompleteHandover) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCompleteHandover) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCompleteHandover) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCompleteHandoverResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCompleteHandoverResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCompleteHandoverResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewGovernor) > 0 {
		i -= len(m.NewGovernor)
		copy(dAtA[i:], m.NewGovernor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewGovernor)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgInitiateHandover) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewGovernor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgInitiateHandoverResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ActivationHeight != 0 {
		n += 1 + sovTx(uint64(m.ActivationHeight))
	}
	return n
}

func (m *MsgCompleteHandover) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCompleteHandoverResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NewGovernor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgInitiateHandover) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitiateHandover: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitiateHandover: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewGovernor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewGovernor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInitiateHandoverResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitiateHandoverResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitiateHandoverResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivationHeight", wireType)
			}
			m.ActivationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActivationHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCompleteHandover) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCompleteHandover: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCompleteHandover: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCompleteHandoverResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCompleteHandoverResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCompleteHandoverResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewGovernor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewGovernor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
