#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Render a whitepaper Markdown canon into a styled HTML carrier.

The Chinese and English editions share one visual shell (the dark-gold
collector theme) and are generated by this single renderer, so neither can
drift from its Markdown source.  The shell is lifted from an existing HTML
file, which lets the two editions keep different UI strings while sharing
every byte of CSS.

The previous HTML carrier was produced by a converter that emitted table rows
out of order (every <tr> was flushed at the end of the document), which broke
the whole appendix.  This renderer regenerates both the table of contents and
the body from the canonical Markdown, so that can never happen again.

Usage:
  python scripts/render_whitepaper_html.py                       # Chinese ed.
  python scripts/render_whitepaper_html.py --lang en \\
      --src WHITEPAPER.md --dst docs/whitepaper_en.html \\
      --shell-from docs/whitepaper_en.html
"""

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SHELL_END = '  <div class="sidebar-header">\n    <a href="index.html">&larr; %s</a>\n  </div>\n'

RAW_PASSTHROUGH = ('<div align="center">', "</div>")

UI = {
    "zh": {"back": "返回首页", "html_lang": "zh-CN"},
    "en": {"back": "Back to Home", "html_lang": "en"},
}


def esc(text):
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def inline(text):
    """Inline markdown -> HTML.  Code spans are protected from further passes."""
    out = esc(text)
    spans = []

    def stash(match):
        spans.append(match.group(1))
        return "\x00%d\x00" % (len(spans) - 1)

    out = re.sub(r"`([^`]+)`", stash, out)
    out = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", out)
    out = re.sub(r"(?<![\*\w])\*([^*\n]+)\*(?!\*)", r"<em>\1</em>", out)
    out = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', out)
    out = re.sub(r"\x00(\d+)\x00", lambda m: "<code>%s</code>" % spans[int(m.group(1))], out)
    return out


def slug(text):
    """GitHub-compatible anchor, matching the anchors already published."""
    s = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    s = re.sub(r"`([^`]+)`", r"\1", s)
    s = s.lower().strip()
    s = re.sub(r"[\s\u3000]+", "-", s)
    s = re.sub(r"[^\w\u4e00-\u9fff\-]", "", s, flags=re.UNICODE)
    return s


def render(md_lines):
    body = []
    toc = []
    i = 0
    n = len(md_lines)

    def flush_paragraph(buf):
        if buf:
            body.append("<p>%s</p>\n" % inline(" ".join(buf).strip()))
            del buf[:]

    para = []

    while i < n:
        line = md_lines[i].rstrip("\n")
        stripped = line.strip()

        # blank line -> paragraph break
        if not stripped:
            flush_paragraph(para)
            i += 1
            continue

        # raw html passthrough (the centred cover block)
        if stripped in RAW_PASSTHROUGH:
            flush_paragraph(para)
            body.append(stripped + "\n\n")
            i += 1
            continue

        # horizontal rule
        if re.fullmatch(r"-{3,}", stripped):
            flush_paragraph(para)
            body.append("<hr>\n")
            i += 1
            continue

        # fenced code block
        if stripped.startswith("```"):
            flush_paragraph(para)
            i += 1
            code = []
            while i < n and not md_lines[i].strip().startswith("```"):
                code.append(md_lines[i].rstrip("\n"))
                i += 1
            i += 1  # closing fence
            body.append("<pre><code>%s\n</code></pre>\n\n" % esc("\n".join(code)))
            continue

        # heading
        m = re.match(r"^(#{1,4})\s+(.*)$", stripped)
        if m:
            flush_paragraph(para)
            level = len(m.group(1))
            title = m.group(2).strip()
            anchor = slug(title)
            body.append('<h%d id="%s">%s</h%d>\n\n' % (level, anchor, inline(title), level))
            toc.append((level, anchor, title))
            i += 1
            continue

        # table
        if stripped.startswith("|"):
            flush_paragraph(para)
            rows = []
            while i < n and md_lines[i].strip().startswith("|"):
                rows.append(md_lines[i].strip())
                i += 1

            def cells(row):
                parts = row.strip().strip("|").split("|")
                return [c.strip() for c in parts]

            header = cells(rows[0])
            data = rows[2:] if len(rows) > 1 and re.fullmatch(r"[\s|:\-]+", rows[1]) else rows[1:]
            body.append('<div class="table-wrap"><table>\n')
            body.append("<tr>%s</tr>\n" % "".join("<th>%s</th>" % inline(c) for c in header))
            for row in data:
                body.append("<tr>%s</tr>\n" % "".join("<td>%s</td>" % inline(c) for c in cells(row)))
            body.append("</table></div>\n\n")
            continue

        # blockquote
        if stripped.startswith(">"):
            flush_paragraph(para)
            quote = []
            while i < n and md_lines[i].strip().startswith(">"):
                quote.append(re.sub(r"^>\s?", "", md_lines[i].strip()))
                i += 1
            body.append("<blockquote>\n")
            chunk = []
            for q in quote:
                if q.strip():
                    chunk.append(q.strip())
                elif chunk:
                    body.append("<p>%s</p>\n" % inline(" ".join(chunk)))
                    chunk = []
            if chunk:
                body.append("<p>%s</p>\n" % inline(" ".join(chunk)))
            body.append("</blockquote>\n\n")
            continue

        # unordered list
        if re.match(r"^[-*]\s+", stripped):
            flush_paragraph(para)
            body.append("<ul>\n")
            while i < n and re.match(r"^[-*]\s+", md_lines[i].strip()):
                item = re.sub(r"^[-*]\s+", "", md_lines[i].strip())
                body.append("<li>%s</li>\n" % inline(item))
                i += 1
            body.append("</ul>\n\n")
            continue

        # ordered list
        if re.match(r"^\d+\.\s+", stripped):
            flush_paragraph(para)
            body.append("<ol>\n")
            while i < n and re.match(r"^\d+\.\s+", md_lines[i].strip()):
                item = re.sub(r"^\d+\.\s+", "", md_lines[i].strip())
                body.append("<li>%s</li>\n" % inline(item))
                i += 1
            body.append("</ol>\n\n")
            continue

        para.append(stripped)
        i += 1

    flush_paragraph(para)
    return "".join(body), toc


def render_toc(toc):
    out = []
    pad = {1: 0, 2: 16, 3: 32, 4: 48}
    for level, anchor, title in toc:
        out.append(
            '<a class="toc-h%d" href="#%s" style="padding-left:%dpx">%s</a>\n'
            % (level, anchor, pad.get(level, 48), esc(title))
        )
    return "".join(out)


def take_shell(html, lang):
    """Return the reusable prefix of an existing carrier, localised."""
    marker = SHELL_END % UI[lang]["back"]
    idx = html.find(marker)
    if idx < 0:
        # tolerate a shell written with the other language's UI strings
        m = re.search(r'^  <div class="sidebar-header">\n(?:.*\n)*?  </div>\n',
                      html, re.M)
        if not m:
            return None
        shell = html[: m.end()]
        shell = re.sub(r'(&larr; )[^<]*', r'\1' + UI[lang]["back"], shell)
        return shell
    return html[: idx + len(marker)]


def cover_title(md_lines):
    """The <title> tag text: first heading, an em dash, then the subtitle."""
    heads = []
    for line in md_lines:
        m = re.match(r"^(#{1,3})\s+(.+?)\s*$", line.rstrip("\n"))
        if m:
            t = re.sub(r"[`*]", "", m.group(2)).strip()
            heads.append(t)
            if len(heads) == 2:
                break
    return " — ".join(heads)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=os.path.join(ROOT, "WHITEPAPER_CN.md"))
    ap.add_argument("--dst", default=os.path.join(ROOT, "docs", "whitepaper.html"))
    ap.add_argument("--shell-from", default=None,
                    help="HTML file to lift the visual shell from (default: --dst)")
    ap.add_argument("--lang", default="zh", choices=("zh", "en"))
    args = ap.parse_args()

    shell_from = args.shell_from or args.dst

    with open(args.src, "r", encoding="utf-8") as fh:
        md_lines = fh.readlines()
    with open(shell_from, "r", encoding="utf-8") as fh:
        current = fh.read()

    shell = take_shell(current, args.lang)
    if shell is None:
        sys.exit("cannot locate sidebar shell in %s" % shell_from)

    # localise the shell chrome
    shell = re.sub(r'<html lang="[^"]*">', '<html lang="%s">' % UI[args.lang]["html_lang"], shell)
    title = cover_title(md_lines)
    if "<title>" in shell:
        shell = re.sub(r"<title>.*?</title>", "<title>%s</title>" % esc(title), shell,
                       count=1, flags=re.S)

    body, toc = render(md_lines)
    html = shell + render_toc(toc) + "</nav>\n<main class=\"main\">\n" + body + "\n</main>\n</body>\n</html>\n"

    with open(args.dst, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(html)

    print("rendered %s  (%d headings, %d bytes)" % (args.dst, len(toc), len(html)))


if __name__ == "__main__":
    main()
